### ISSUE TITLE
ARM-based support?

### ISSUE THREAD

**Issue by TimHeckel** [Opster/opensearch-k8s-operator#114]
Firstly, thanks so much for this initiative! I attempted to install the operator on a c6g.4xlarge Graviton (ARM) based processor and received the below error:

`standard_init_linux.go:228: exec user process caused: exec format error`

Has this come up before?

**Comment by prudhvigodithi** [comment]
Hey @TimHeckel Is this the error you get if you compile the operator or using the helm?
assuming with  compiling the operator, once you ran `make build manifests`, you should see `testbin/` folder being created, inside that folder can you modify the `setup-envtest.sh ` script and point `goarch` to `arm64` and give it a try?

**Comment by TimHeckel** [comment]
Hi - I just used the helm chart. I will try compiling! Thanks

**Comment by prudhvigodithi** [comment]
Then I would assume image might not be multi arch supported.

**Comment by idanl21** [comment]
Hey! we just added on the latest release, just add -ARM on the manager image name

**Comment by TimHeckel** [comment]
Thanks! I will try it out when I get a chance. Appreciate all the effort here.
