### ISSUE TITLE
Resource requirements missing from cluster bootstrap pod 

### ISSUE THREAD

**Issue by vanveele** [Opster/opensearch-k8s-operator#120]
The bootstrap pod does not declare any required resources and is also not configurable via CRD.
The [BootstrapPod](https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/builders/cluster.go#L497) when launched on a cluster with resource defaults defined (to ensure that all pods are configured with limits) may fail to complete a bootstrap if the configured defaults are too small to accommodate the [hard-coded Java heap opts](https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/builders/cluster.go#L560).
Both the pod resources and the bootstrap java opts should be exposed via the CRD as configurable parameters or else a default resource limit configured to match the Java opts.

**Comment by vanveele** [comment]
[draft PR](https://github.com/Opster/opensearch-k8s-operator/pull/121) created to implement. I have tried to match the style of the existing nodes definitions. please let me know if I am on the right track.

**Comment by idanl21** [comment]
implement and marged https://github.com/Opster/opensearch-k8s-operator/pull/121
