### ISSUE TITLE
operator should be installed into whatever namespace helm is used in

### ISSUE THREAD

**Issue by segalziv** [Opster/opensearch-k8s-operator#122]
No namespace name should be set in the values.yaml. The operator should be installed into whatever namespace helm is used in (by default the selected namespace of kubectl or the one specified as helm install -n <namespace>). Helm offers {{ .Release.Namespace }} for that.

**Comment by idanl21** [comment]
Uploaded New PR about it, also changed on artifactHub.io repol

**Comment by idanl21** [comment]
fixed in the latest release

**Comment by ekarlso** [comment]
There is still namespace issues with the chart btw..
