### ISSUE TITLE
Allow override of BusyBox image

### ISSUE THREAD

**Issue by ekarlso** [Opster/opensearch-k8s-operator#127]
It should be possible to override the image for BusyBox either at the operator level as a argument when starting or as a part of the CRD?

**Comment by idanl21** [comment]
Hey, from my experience that option isn’t exist yet. for which purpose do you need it ? @ekarlso 
Thanks !

**Comment by ekarlso** [comment]
@idanl21 if you use a private image mirror for you stuff it's needed :)

**Comment by kfox1111** [comment]
Yeah. Sites that have isolated networks would need this.

**Comment by idanl21** [comment]
Hey @kfox1111 and @ekarlso, will add on the next version.

**Comment by Mezzenine** [comment]
@idanl21 can you explain how I overwrite the busyBox image? I couldn't find any helm values, where I can specify the image and/or image repository

**Comment by akshaypolji** [comment]
Hey @Mezzenine were you able to find any workaround? 
Hello @idanl21 / @swoehrl-mw , I see that new version was releases recently but still the busybox images are referring to ecr.aws repository.
Just wanted to check if this enhancement is still under development. 
Thanks!

**Comment by swoehrl-mw** [comment]
Hi @akshaypolji. Afaik @idanl21 is still working on this.

**Comment by akshaypolji** [comment]
@swoehrl-mw , Thanks for the update. @idanl21 Looking forward it!

**Comment by akshaypolji** [comment]
> Yeah. Sites that have isolated networks would need this.

Ditto!

**Comment by JoostvdB94** [comment]
I'm going to re-open this issue as it hasn't been fixed.

**Comment by chenyg0911** [comment]
How about the issue?  the same issue to deploy in internal k8s which can't access internet.

**Comment by swoehrl-mw** [comment]
Implemented in PR #326.
Closing this issue as completed.
