### ISSUE TITLE
explicitly list supported OpenSearch & OpenSearch Dashboards versions

### ISSUE THREAD

**Issue by rursprung** [Opster/opensearch-k8s-operator#138]
currently neither the README nor the release notes (on GitHub) list the versions of OpenSearch and OpenSearch Dashboards which are supported by this version of the operator.

it'd be great if:
* the README would contain a compatibility matrix for all still supported operator versions (i.e. the version of the README at the tip of the master branch would always reflect the current state, checking the README as of an older version will just confirm the compatibility for that version w/o stating whether it's still supported in any way)
* the release notes would always list the currently compatible version range for that operator version

**Comment by prudhvigodithi** [comment]
Agree @rursprung, we need a compatibility matrix.
@idanl21 @segalziv @dbason @swoehrl-mw

**Comment by idanl21** [comment]
Created proper issue for that
