### ISSUE TITLE
Create snapshot and restore service

### ISSUE THREAD

**Issue by shahar35** [Opster/opensearch-k8s-operator#15]
Service responsibility:
1. Snapshot creation
2. Snapshots status
3. Schedule restore.

**Comment by setiah** [comment]
FYI - something to leverage. OpenSearch 2.1 released Snapshot Management feature that provides automated snapshot creation and deletion via policies and has a nice UI available to list/manage snapshots on Dashboard.

**Comment by idanl21** [comment]
Implemented on that PR - https://github.com/Opster/opensearch-k8s-operator/pull/370
waiting for marge, closing the issue for now
