### ISSUE TITLE
ValidationError for additionalConfig

### ISSUE THREAD

**Issue by steschuser** [Opster/opensearch-k8s-operator#155]
Adding *additionalConfig* results in an ValidationError

`error: error validating "values/opensearch-cluster.yaml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards): unknown field "additionalConfig" in io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards; if you choose to ignore these errors, turn validation off with --validate=false`

This conflicts with the Userguide 

https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#configuring-opensearch_dashboardsyml

**Comment by albertollamaso** [comment]
@steschuser can you share the YAML file you are applying.

**Comment by xikunyu** [comment]
@albertollamaso I ran into the same problem.

here is my yaml file

`[root@eks-test opensearch]# kubectl apply -f cluster.yaml
error: error validating "cluster.yaml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards): unknown field "additionalConfig" in io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards; if you choose to ignore these errors, turn validation off with --validate=false
[root@eks-test opensearch]# cat cluster.yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
  namespace: opensearch-system
spec:
  general:
    serviceName: opensearch
    version: 1.3.1
  #security:
  #  config:  # Everything related to the securityconfig
  #    securityConfigSecret:
  #      name:  securityconfig-secret
      #adminSecret:
      #  name:  # Name of a secret that contains the admin client certificate
      #adminCredentialsSecret:
      #  name:  admin-secret
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    additionalConfig:
      opensearch_security.multitenancy.enabled: "true"
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters-data-hot
      replicas: 2
      diskSize: "5Gi"
      NodeSelector:
      resources:
         requests:
            memory: "1Gi"
            cpu: "500m"
         limits:
            memory: "1Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
        - "ingest"
      additionalConfig:
        node.attr.type: hot
    - component: masters-data-cold
      replicas: 1
      diskSize: "5Gi"
      NodeSelector:
      resources:
         requests:
            memory: "1Gi"
            cpu: "500m"
         limits:
            memory: "1Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
        - "ingest"
      additionalConfig:
        node.attr.type: cold
`

**Comment by albertollamaso** [comment]
@xikunyu I was able to create a cluster using your YAML file. Can you try with latest version ?. Perhaps you can share the version of opensearch-k8s-operator you are using.

**Comment by xikunyu** [comment]
@albertollamaso I installed the chart from opensearch-operator-1.0.1.tar.gz which was downloaded from release page.

```
[root@eks-test opensearch]# helm ls -n opensearch-system
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
opensearch-operator     opensearch-system       1               2022-06-01 14:48:55.404801806 +0800 CST deployed        opensearch-operator-1.0.1       1.16.0
```

**Comment by swoehrl-mw** [comment]
Looks like the CRD distributed with the helm chart is not up-to-date and does not contain the spec for the `dashboards.additionalConfig`.

**Comment by idanl21** [comment]
Hey @xikunyu, can you please try to delete the CRD from the cluster and reinstall it? it looks like you are working with an older version

**Comment by xikunyu** [comment]
@idanl21 Which version should I use? 1.0.2 chart version? I'll take a try. Thank you.

[root@eks-test ~]# helm search repo opensearch-operator/opensearch-operator
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
opensearch-operator/opensearch-operator 1.0.2           1.16.0          The OpenSearch Operator Helm chart for Kubernetes

**Comment by xikunyu** [comment]
@idanl21 Helm chart version 1.0.2 also got this problem.Is there a latest version?

**Comment by albertollamaso** [comment]
This PR rsolves the issue: https://github.com/Opster/opensearch-k8s-operator/pull/175/files
Needs to be merged and update Helm chart repo with a new version th
