### ISSUE TITLE
Disable namespace creation

### ISSUE THREAD

**Issue by mixitgit** [Opster/opensearch-k8s-operator#16]
OS cluster is currently namespaced although it creates a separate namespace to deploy cluster
I think for more convenience it should either be namespaced and deploy cluster in the same namespace where crd has been created, or should be a cluster resource and deploy cluster in a namespace specified in spec
In my opinion namespace management via operator makes sense when crd requires multiple namespaces, otherwise we will have some pain managing full lifecycle in terms of PVC management
There is a number of operators for orchestrating databases that I used to work with and all of them create clusters in the same namespace where crd is created (cassandra, vicroriametrics, etcd etc)

**Comment by mixitgit** [comment]
I think we should switch to creation of cluster in the same namespace where CRD has been created, unless there is a chance we will need to create multiple namespaces for multiple components (like single controlplane namespace and separate namespaces for different components)

**Comment by idanl21** [comment]
Hi Michael, thanks for the issue.
your idea is part of our progress plan, thats an update that we will add in the next versions.

**Comment by segalziv** [comment]
@idanl21 any update here? is it done?
