### ISSUE TITLE
lifecycle for dashboard and nodePools

### ISSUE THREAD

**Issue by elkh510** [Opster/opensearch-k8s-operator#163]
Could you pls add ability for configure pod [lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/) for dashboard and nodePools.
This can be useful for create index, index pattern, index rotation policy etc.
Thank you!

**Comment by swoehrl-mw** [comment]
Hi @elkh510. Could you please go into more detail on what you would like to see, maybe with an example how the cluster spec yaml could look like and how that plays together with pod lifecycle?
We have an item on the roadmap to potentially add index lifecyclemanagement to the operator. Currently its only a headline but I can imagine it being either options in the cluster spec or maybe new custom resources to create and manage index patterns and configure index management features of opensearch. Is that the direction you want to have?

**Comment by elkh510** [comment]
hi
>Could you please go into more detail on what you would like to see,

at the first stage, it might make sense to do something like this
dashboard [example](https://github.com/elastic/helm-charts/blob/v7.17.3/kibana/values.yaml#L168-L176)
opensearch [example](https://github.com/elastic/helm-charts/blob/main/elasticsearch/values.yaml#L275-L293)
this option is not bad, because with minimal edits it gives a lot of flexibility, since you can execute any commands, which in turn allows you to perform almost any configuration through rest api
> new custom resources to create and manage index patterns and configure index management features of opensearch

it would be great in the long perspective
I mean through the CRD you can create:
 - index
 - index pattern  (dashboard)
 - rotation policy
 - additional users
 but the moment remains debatable about what exactly can be created through CRD.
so ideally have both of the above options

**Comment by dbason** [comment]
I'm not sure pod lifecycle events are the correct place for these sort of operations.  I guess you could argue that there could be room to put some pre stop ones in for draining nodes, but this logic is already in the controller.

The problem with this is it can lead to weird states where the commands aren't properly idempotent, particularly if a multi-node cluster.  We definitely have more CRD options (users etc) on the roadmap, so I'm going to close this issue out.
