### ISSUE TITLE
Security Settings - post cluster creation reload

### ISSUE THREAD

**Issue by ekarlso** [Opster/opensearch-k8s-operator#172]
Is it not the intention that security settings will be automatically reloaded after the cluster is created if you update the secret?

**Comment by swoehrl-mw** [comment]
Hi @ekarlso. Yes, that is how it should work. The operator checks for changes in the content of the securityconfig secret and reapplies it if there is a diff.

If this does not work for you could you please provide instructions/details to reproduce?

**Comment by idanl21** [comment]
Hey @ekarlso, can you please post your status on that issue ? Thanks!

**Comment by ekarlso** [comment]
@swoehrl-mw no it is not reloading in our case, is it possible to debug this somehow or add logging for it ?

**Comment by ekarlso** [comment]
@idanl21 @swoehrl-mw are you guys on slack or anything to discuss?

**Comment by segalziv** [comment]
@ekarlso yes we do use a slack channel. I see your email on your GitHub profile, I can invite you to that channel if you wish.

**Comment by ekarlso** [comment]
Ah yes, kicking the tires of the job worked totally fine!
