### ISSUE TITLE
Opensearch Dashboards startup probe

### ISSUE THREAD

**Issue by danielbichuetti** [Opster/opensearch-k8s-operator#181]
Hi,

Making usage of operator using OpenSearch Dashboard 2.0.0 per default sets health route authentication. When trying to disable the authentication route for /api/status so kube-probe could check it, I get invalid field:

additionalConfig:
      opensearch_security.auth.unauthenticated_routes: |
        ['/api/reporting/stats', '/api/status']

On user guide it says for opensearch_dashboard.yml setup we could use this field. Any changes on last version ?

`error: error validating ".\\opensearch-cluster.yaml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards): unknown field "additionalConfig" in io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by swoehrl-mw** [comment]
Hi @danielbichuetti. With the merging of #175 and helm chart version 1.0.3 this is now fixed. Can you please try again?

**Comment by danielbichuetti** [comment]
Hi @swoehrl-mw. Sorry for the delay, I'll take a look this weekend. Thank you very much !

**Comment by idanl21** [comment]
Problem solved, closing issue. Thanks !
