### ISSUE TITLE
how to install prometheus plugin ? 

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#193]
Is there a way to install Prometheus exporter plugin for each node in the cluster

**Comment by rursprung** [comment]
i guess you could just build your own custom image with the exporter (and all relevant config for it) in it? depending  on how you scrape your nodes this might however not work: if you use the k8s annotations on the pods then this won't work as they won't be present (the operator currently wouldn't know that it'd have to add them).

there's however an open ticket to add proper support for the prometheus exporter: #18

**Comment by idanl21** [comment]
Hey @KannappanSomu, we are working on a new feature that will install the plugin, service and service monitor.
hope to be ready on next release

**Comment by ibotty** [comment]
See #200 and #201

**Comment by idanl21** [comment]
Hey @KannappanSomu, take a look on #200 , will be added to the next release
