### ISSUE TITLE
[BUG] Cluster yaml general.httpPort does not work other than 9200.

### ISSUE THREAD

**Issue by prudhvigodithi** [Opster/opensearch-k8s-operator#196]
Adding the following 
```  
general:
    httpPort: 9400
```
will fail the cluster to start
`ERR: Seems there is no OpenSearch running`
This httpPort with existing setup is added as part of ProbeHandler TCPSocket, cluster by default listens on port 9200, so using any other port other than 9200 will fail the cluster to start up 
https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch.al2.dockerfile#L92

This issue was found as part of tests associated with OpenSearch Kubernetes Operator with 2.0.0
https://github.com/Opster/opensearch-k8s-operator/issues/176

**Comment by swoehrl-mw** [comment]
Afaik the `EXPOSE` directive in dockerfiles is irrelevant for kubernetes pods. I think the problem is that we jut forgot to set the `http.port` option in the opensearch config if the port is non-default.

**Comment by prudhvigodithi** [comment]
Closing this issue as fix is pushed with PR https://github.com/Opster/opensearch-k8s-operator/pull/198
