### ISSUE TITLE
Add mechanism to install plugins

### ISSUE THREAD

**Issue by segalziv** [Opster/opensearch-k8s-operator#200]
Currently, in order to install plugins, users would have to build an image with the required plugins installed and use that image instead of the default image.

Plugins are needed for snapshots repo and other cases, therefore it is very important that installing plugins would be supported natively in the operator. 

The idea is that the user could define the plugins he wishes to install in a new and separate CRD and that the operator would pick up the missing plugins, install them, and perform a rolling restart for that to take effect.

**Comment by idanl21** [comment]
Already started to work about it, hope to create first PR tomorrow

**Comment by idanl21** [comment]
https://github.com/Opster/opensearch-k8s-operator/pull/201

**Comment by idanl21** [comment]
Added on latest release
