### ISSUE TITLE
How to add pod anti affinity for cluster pods ? 

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#202]
In order to avoid both primary and replica shard ending up on same kubernetes node,
I would need to use pod anti affinity for cluster pods .

Is this possible today ? its missing in documents & examples

**Comment by idanl21** [comment]
Hey @KannappanSomu, today we only support PodAffinity and not Anti Affinity. i will upload a Pr on it. it will add to the next release

**Comment by idanl21** [comment]
Hey @KannappanSomu, yes. you can add `NodeAffinity/PodAffinity/PodAntiAffinity` to every nodeGroup and also to the bootstrap pod under `Affinity` key :)

**Comment by KannappanSomu** [comment]
thanks !
