### ISSUE TITLE
ImagePullSecrets not working

### ISSUE THREAD

**Issue by karthikbattaram** [Opster/opensearch-k8s-operator#205]
Hi everyone, we are trying to deploy opensearch cluster using the operator and in the yaml of type OpesearchCluster which is used to deploy the cluster, under the section spec general, the parameter for setting image pull secrets doesn't seem to be working, also the parameter called image does not seem to be working, had to set default repo in order to pull image from private registry but now we are getting image pull back off error due to no basic auth credentials.

It doesnt seem to be an issue with the secret containing docker registry credentials as other pods are able to pull images using the same secret.

Not sure what we are missing here, any help would be appreciated.
Thanks!

**Comment by karthikbattaram** [comment]
Hi @swoehrl-mw 
Actually we are not using helm charts we are using manifests we got from artifact hub, 
this is the version of the operator we are currently using - public.ecr.aws/opsterio/opensearch-operator:v1.0

**Comment by NoorKumar** [comment]
I am also facing same issue, I just clones the latest code from git repo and running the operator locally. looks latest code also ignoring the imagePullSecrets. I have provided imagePullSecrets in the spec general section but while creating the cluster it says authentication required. can anyone please help

**Comment by karthikbattaram** [comment]
It works for me with operator version 1.1

**Comment by swoehrl-mw** [comment]
Hi @NoorKumar . Can you share your cluster yaml? If you are running `main` from git, then imagePullSecrets should work.
Can you please also check your `OpensearchCluster` spec after creating it (and the operator started its work) and see if the `imagePullSecrets` part is still in it? Because in the old bug the field vanished from the spec after the operator updated it during cluster creation.

**Comment by NoorKumar** [comment]
Hi @swoehrl-mw 
Yes, I am running from main branch and I see imagePullSecrets is there in the os spec.

This is the cluster yaml file
`apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster
  namespace: opensearch-demo
spec:
  general:
    image: <image>
    version: <image tag>
    imagePullSecrets:
      - name: imageregistrykey
    httpPort: 9200
    vendor: opensearch
    serviceName: my-cluster
  dashboards:
    version: 1.3.0
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      labels:
        "mylabel": master
      env:
        - name: env1
          value: "master"
      replicas: 2
      diskSize: "1Gi"
      NodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "master"
        - "data"
    - component: nodes
      labels:
        "mylabel": data
      env:
        - name: env1
          value: "data"
      replicas: 2
      diskSize: "1Gi"
      NodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "data"
    - component: coordinators
      labels:
        "mylabel": data
      env:
        - name: env1
          value: "data"
      replicas: 1
      diskSize: "1Gi"
      NodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "ingest"
`


Below is the OpensearchCluster spec after creating

`spec:
  bootstrap:
    resources: {}
  confMgmt:
    smartScaler: true
  dashboards:
    enable: true
    opensearchCredentialsSecret: {}
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    version: 1.3.0
  general:
    httpPort: 9200
    image: <image>
    imagePullSecrets:
    - name: imageregistrykey
    serviceName: my-cluster
    vendor: opensearch
  nodePools:
  - component: masters
    diskSize: 1Gi
    env:
    - name: env1
      value: master
    labels:
      mylabel: master
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi
    roles:
    - master`

**Comment by swoehrl-mw** [comment]
In that case, @NoorKumar it is not the bug I mentioned previously. Can you check the started pods (`my-cluster-master-0` and so on) if they have the imagePullSecrets in their specs?

**Comment by swoehrl-mw** [comment]
@NoorKumar If the pods have the impagePullSecret then I suspect the problem lies not with the operator but more with the kubernetes cluster or the pullSecret itself.

**Comment by idanl21** [comment]
Hey @karthikbattaram, is the `impagePullSecret` key is found on your cluster YAML?
