### ISSUE TITLE
not able to set extraVolumeMounts and volumes

### ISSUE THREAD

**Issue by TH12380923** [Opster/opensearch-k8s-operator#218]
my usecase is to add new saml metafile file into the opensearch and right now it is not possible and looking for options to attach the volume from config map.  The operator is not allowing me to modify any kubernetes resources. Is it possible to modify the kubernetes resources post deployment using the operator?

**Comment by dbason** [comment]
We're currently working on the option to add volumes in to the resources.  This should land pretty soon.

**Comment by dbason** [comment]
This will be solved with #213

**Comment by hpkuppuraj** [comment]
@dbason , Thanks as this is some feature that will help a lot. Is there any plan to make the configmap or secret to edit. Looks like this is not possible when the resources are deployed using this operator.

**Comment by dbason** [comment]
The operator won't manager the secrets or configmaps to be mounted.  Because these are completely arbitrary we would need to basically include the entire resource definition, at which point it's just as easy to create the resource separately.

There is an option to reload the operator when the content of the secret or configmap changes, would this achieve what you need?

**Comment by hpkuppuraj** [comment]
Yes, this looks like a solution where we include the resource definition to create the resources separately. However, if we create the resources separately, we need to include those resources into the pod definition file which at the moment i believe is work in progress as per this thread https://github.com/Opster/opensearch-k8s-operator/pull/213

**Comment by dbason** [comment]
That looks like it might be a bug when certs are mounted looking at the values from the issue.  Would you be able to share your custom resource yaml with us?

Another thing to note is that it looks like you're trying to mount a single additional file into the config directory.  We currently don't have the option for subPath mounts - you will need to mount that to another folder (check out the userguide for examples).

**Comment by hpkuppuraj** [comment]
@dbason , Thanks for the fast response. May i know how can i share the custom resource as a file 
I even tried mounting the configMap/Secret as it is without subpath, but no luck. If I view the CRD inside the cluster i could see additionalVolume attributes but the OpenSearchCluster resource doesnt have any mention of additionalVolume attribute. 

Below is the cluster manifest file. 

`apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-os
  namespace: monitoring-events
spec:
  general:
    version: 2.0.0
    httpPort: 9200
    vendor: opensearch
    serviceName: opensearch-os
    additionalVolumes:
    - name: metafile
      path: /usr/share/opensearch/config/
      secret:
        secretName: saml-metafile-secret
  dashboards:
    version: 2.0.0
    enable: true
    tls:
      enable: true
      generate: true
    replicas: 1
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  security:
    config:
      securityConfigSecret:
##Pre create this secret with required security configs, to override the default settings
       name: securityconfig-secret
      adminSecret:
       name: opensearch-os-admin-cert

    tls:
      transport:
        generate: true
        perNode: true
      http:
        generate: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "master"
    - component: data
      replicas: 2
      diskSize: "100Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"`

**Comment by dbason** [comment]
That's fine, that's the file I was looking for.  I will do some testing and see if I can narrow down what is happening.

**Comment by dbason** [comment]
I haven't been able to replicate the problem, so any logs you can share would be very useful.  Also it might be worth manually building the docker image yourself just incase there was a problem with the CI

**Comment by hpkuppuraj** [comment]
I tried the suggested change, but not working. So what i have decided to add the saml meta file as part of the security config secret, which i have a control to edit, and set the security configuration path to /usr/share/opensearch/config/opensearch-security/metafile.xml. Will see this one works for my usecase or not. But I am aware that we should not place any configs in the opensearch-security directory.

**Comment by hpkuppuraj** [comment]
@dbason , just an update here. Still not able to set the extravolume. However, i have deployed the custom configuration as part of the security configuration. So far no issues has been observed.

**Comment by Leweyy** [comment]
Also looks like the Helm CRDs dont support this general.additionalVolumes field yet

**Comment by Prashantpv** [comment]
Is there any update on this, I am also not able to add additionalVolumes, getting below error:

error: error validating "opensearch-cluster.yaml": error validating data: [ValidationError(OpenSearchCluster.spec): unknown field "additionalVolumes" in io.opster.opensearch.v1.OpenSearchCluster.spec, ValidationError(OpenSearchCluster.spec.general): unknown field "config" in io.opster.opensearch.v1.OpenSearchCluster.spec.general, ValidationError(OpenSearchCluster.spec.general): unknown field "tls" in io.opster.opensearch.v1.OpenSearchCluster.spec.general]; if you choose to ignore these errors, turn validation off with --validate=false

`apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: spike
  namespace: elastic-stack
spec:
  general:
    AdditionalVolumes:
    - name: cloud-credentials
      secret:
        secretName: opensearch-snapshots
    version: 1.3.0
    httpPort: 9200
    vendor: opensearch
    serviceName: opensearch
    pluginsList: ["repository-s3","https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/1.3.0.0/prometheus-exporter-1.3.0.0.zip"]
    tls:
      transport:
        generate: true
      http:
        generate: true
    config:
      securityConfigSecret:
        name: securityconfig-secret  
  security:
  dashboards:
    version: 1.3.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
    tls:
      enable: true
      generate: true
    additionalConfig:
      opensearch_security.auth.type: "saml"
      server.xsrf.whitelist: |
        ["/_opendistro/_security/saml/acs"] 
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 2
      diskSize: "5Gi"
      nodeSelector: 
        kops.k8s.io/instancegroup: monitoring-nodes-1
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: monitoring
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/credentials
      roles:
        - "master"
    - component: nodes
      replicas: 1
      diskSize: "5Gi"
      nodeSelector:
        kops.k8s.io/instancegroup: monitoring-nodes-1
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: monitoring
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/credentials
      roles:
        - "data"
`
Chart: 2.0.4

**Comment by swoehrl-mw** [comment]
The fields were added to the helm chart CRD in #273. Once we cut the next release this should work.
