### ISSUE TITLE
Resizing PVC throws errors

### ISSUE THREAD

**Issue by hpkuppuraj** [Opster/opensearch-k8s-operator#224]
I have provisioned an opensearch cluster with 100g persistence volume for data node and later tried to increase the volume to 500g. The operator throws error in this case. From the logs I found the reason is the service account couldn't list the resource "Persistence Volume claims" On closer look, the operator deploys the cluster role which doesnt have the permission set for PVC. 

After setting the below permission in the clusterrole, able to resize the pvc. 

```
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - get
  - watch
  - update
```

Error message for the reference: 

```
1.6581332636462932e+09	DEBUG	events	Normal	{"object": {"kind":"OpenSearchCluster","namespace":"monitoring-opensearch","name":"opensearch","uid":","apiVersion":"opensearch.opster.io/v1","resourceVersion":"119203560"}, "reason": "PVC", "message": "Starting to resize PVC monitoring-opensearch/opensearch-data from 100Gi to  500Gi "}
1.6581332636599283e+09	INFO	controller.opensearchcluster	The claimName identified as data-opensearch-data-0	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "opensearch", "namespace": "monitoring-opensearch"}
W0718 08:34:23.662076       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:opensearch-operator-system:opensearch-operator-controller-manager" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope
```

**Comment by prudhvigodithi** [comment]
Hey @hpkuppuraj have you tried with latest helm chart ?
```
helm install opensearch-operator opensearch-operator/opensearch-operator --version 2.0.0
```
I was able to scale the PVC, by re-applying the cluster yaml file updating the the `diskSize`. Can you Please try with latest helm chart and update here?

**Comment by prudhvigodithi** [comment]
Hey @hpkuppuraj can you please update here after trying with `2.0.0` helm chart.
Thank you

**Comment by hpkuppuraj** [comment]
@prudhvigodithi , i didnt get a chance to use helm chart, as my cluster was already set using the non-helm way. i need some time as working todays deadlines.

**Comment by prudhvigodithi** [comment]
Hey closing this issue, please feel free to re-open.
Thank you

**Comment by Prashantpv** [comment]
@prudhvigodithi using helm operator 2.0.4 and trying to reduce disk size from 150 GB to 120 GB. Whilst trying to perform this action getting below error:

INFO	controller.opensearchcluster	The existing statefulset VolumeClaimTemplate disk size is: 150Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "spike", "namespace": "elastic-stack"}
1.6626147522995408e+09	INFO	controller.opensearchcluster	The cluster definition nodePool disk size is: 120Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "spike", "namespace": "elastic-stack"}
1.6626147522995608e+09	INFO	controller.opensearchcluster	deleting statefulset while orphaning pods spike-masters	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "spike", "namespace": "elastic-stack"}
1.6626147522996721e+09	DEBUG	events	Normal	{"object": {"kind":"OpenSearchCluster","namespace":"elastic-stack","name":"spike","uid":"0f256818-eca3-4b2e-8e35-5d0fd022c7f7","apiVersion":"opensearch.opster.io/v1","resourceVersion":"461104362"}, "reason": "PVC", "message": "Starting to resize PVC elastic-stack/spike-masters from 150Gi to  120Gi "}
1.6626147523141136e+09	INFO	controller.opensearchcluster	The claimName identified as data-spike-masters-0	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "spike", "namespace": "elastic-stack"}
1.6626147523190734e+09	INFO	controller.opensearchcluster	failed to resize statefulset pvc data-spike-masters-0	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "spike", "namespace": "elastic-stack"}
1.6626147523191125e+09	ERROR	controller.opensearchcluster	Reconciler error	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "spike", "namespace": "elastic-stack", "error": "PersistentVolumeClaim \"data-spike-masters-0\" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227

**Comment by hpkuppuraj** [comment]
@Prashantpv : General practice is you should not reduce the pvc size Hence the validation in place.
