### ISSUE TITLE
New cluster deployment stuck in rolling restart

### ISSUE THREAD

**Issue by mdugas** [Opster/opensearch-k8s-operator#226]
Kubernetes Cluster version: 1.23.5
Operator version: 2.0
OpenSearch Cluster version: 1.3.2

Problem description:
I have been trying to deploy an OpenSearch cluster using the operator in its v2.0 version and unfortunately as soon as the cluster goes green, it starts auto-restarting nodes (pods get deleted and new ones created). This is one rabbithole I haven't found if i'm the root cause or if there's a legit bug with the operator, so here we go with the troubleshooting steps.

I started by looking at the logs on the operator, the debug logs showed that there is a delta, according to the operator, between the current state and the desired state, so the operator sends a patch which is the patch.json file in the zip at the bottom of this ticket.

Once i saw there was a config delta, I decided to pull the running config before the nodes start to reboot and after they've rebooted using `kubectl get sts sati-cold -o yaml` and dumped the two outputs into files. Running the diff command on both files showed that no changes were made. Since I have an admission controller (Kyverno) setuped on the cluster, I disabled the rule set to ensure this wasn't caused by the admission controller and it still showed a delta in the config according to the operator, which supposedly changes the statefulset and triggers a restart. 

Now since the content of the two files were the same, i didn't understand how the operator knew a change happened in the config, so i looked up the code and saw [this block](https://github.com/Opster/opensearch-k8s-operator/blob/d017e93cc4463a7849956641db77bd0636da40a9/opensearch-operator/pkg/reconcilers/rollingRestart.go#L116) which marks the cluster as in need of a rolling restart if the number of updatedReplicas is not equal to the number of replicas. 

Armed with this knowledge, i went and started a watch command to get the status of the sts (`watch -n1 -- "kubectl get sts sati-cold -o yaml | grep -A9 -e '^status\:'"`) and every so often, i saw the updateRevision switches from `sati-cold-7c6978f776` to `sati-cold-7b66864d88` and back to `sati-cold-7c6978f776` a few moments later and when the switch happened the first time, it removed the "updateReplicas" field, which if the rolling restart controller kicked in at that point would initiate a rolling restart for the given statefulset.

I ended up pulling the two revisions and ran them through a diff (both files are in the archive attached to this ticket) and other than the normal "incremental" values that changed, the last-applied annotation changed as well as the block between line 77 and 80 inclusively, which that block the change is simply the order in which the additionalConfigs from the cluster definition get added to the statefulset. I analyzed the last-applied config in both (i found it's a base64 encoded zip file that contains a single file called "original" and that file is the config that was last applied) and they show the same change, which is the order of the configs.

Now this is where i'm stumped, i tried setting the config from the global additionalConfigs down to the invidiual nodepool configs, that didn't work (yes i tried the two different orders). Now what i'm thinking is the operator expects the file to be in a certain order, but Kubernetes changes said order and the operator never becomes satisfied, constantly triggering a change.

If there's something i'm missing out, please let me know, otherwise i'm thinking this is a bug with the operator 🤔 

Files and References:
[package.zip](https://github.com/Opster/opensearch-k8s-operator/files/9154355/package.zip)
Content: 
- oscluster.yaml --> OpenSearchCluster definition that i've been using
- cold_v1.yaml --> statefulSet output for `sati-cold-7c6978f776`
- cold_v2.yaml --> statefulSet output for `sati-cold-7b66864d88`
- patch.yaml --> patch applied by the operator according to the logs.

**Comment by dbason** [comment]
Hi @mdugas, thanks for the report and the in-depth investigation.  This is indeed a bug that has been fixed with #213.  Unfortunately this was merged after the v2.0 release.  You could build a docker image locally and try that to see if it resolves your issue.

**Comment by mdugas** [comment]
Yup that resolves the issue, thanks ^_^
