### ISSUE TITLE
Manage users and roles in AWS managed service

### ISSUE THREAD

**Issue by ccodreanu** [Opster/opensearch-k8s-operator#243]
Hi! I've had a look at the API and at a first glance it seems this is not supported, but what do you think about supporting external clusters and reconcile users and roles with these external clusters?

**Comment by swoehrl-mw** [comment]
Hi @ccodreanu. You are right, it is not supported currently. And IMO I don't see this as a feature as the main job of the operator is deploying and managing an opensearch cluster. Managing users and roles is just a small part of that so I don't see managing users and roles from external clusters as an addition.

**Comment by as42sl** [comment]
That would be a really great feature!

**Comment by idanl21** [comment]
A Users and Roles reconciler was added and merged, take a look the the Docs.
Closing the issue
