### ISSUE TITLE
Version 2.0.2 has insufficient privileges for service account

### ISSUE THREAD

**Issue by dobharweim** [Opster/opensearch-k8s-operator#247]
#### Description

When installing version 2.0.2 the operator-controller-manager container crashes continuously. It seems that the service account is not authorised to list the various different resources.

#### To Reproduce

1. Install version 2.0.2 operator: `helm install opensearch-operator opensearch-operator/opensearch-operator -n opensearch-operator-issue --version 2.0.2`
2. View the logs for the operator-controller-manager container: `k logs -l control-plane=controller-manager -c operator-controller-manager`

#### Logs from container

> I0816 11:07:34.977462       1 request.go:665] Waited for 1.023143129s due to client-side throttling, not priority and fairness, request: GET:https://172.21.0.1:443/apis/kafka.strimzi.io/v1beta1?timeout=32s
> 1.6606480551341822e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
> 1.6606480551345303e+09	INFO	setup	starting manager
> 1.660648055134819e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
> 1.660648055134827e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
> I0816 11:07:35.134942       1 leaderelection.go:248] attempting to acquire leader lease opensearch-operator/a867c7dc.opensearch.opster.io...
> I0816 11:07:50.847194       1 leaderelection.go:258] successfully acquired lease opensearch-operator/a867c7dc.opensearch.opster.io
> 1.6606480708473072e+09	DEBUG	events	Normal	{"object": {"kind":"ConfigMap","namespace":"opensearch-operator","name":"a867c7dc.opensearch.opster.io","uid":"a087bb5b-2d04-4a6d-8d86-c909deb71ffc","apiVersion":"v1","resourceVersion":"953403"}, "reason": "LeaderElection", "message": "opensearch-operator-controller-manager-749cbc65fd-qlzjc_55afdda9-abcd-4f78-b95c-82bb4d2348ad became leader"}
> 1.6606480708475082e+09	DEBUG	events	Normal	{"object": {"kind":"Lease","namespace":"opensearch-operator","name":"a867c7dc.opensearch.opster.io","uid":"6f28024a-eebc-42ef-beb3-91fe041a84f3","apiVersion":"coordination.k8s.io/v1","resourceVersion":"953404"}, "reason": "LeaderElection", "message": "opensearch-operator-controller-manager-749cbc65fd-qlzjc_55afdda9-abcd-4f78-b95c-82bb4d2348ad became leader"}
> 1.6606480708474424e+09	INFO	controller.opensearchrole	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchRole", "source": "kind source: *v1.OpensearchRole"}
> 1.6606480708475385e+09	INFO	controller.opensearchrole	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchRole", "source": "kind source: *v1.OpenSearchCluster"}
> 1.6606480708475494e+09	INFO	controller.opensearchrole	Starting Controller	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchRole"}
> 1.6606480708474584e+09	INFO	controller.opensearchuser	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchUser", "source": "kind source: *v1.OpensearchUser"}
> 1.6606480708476105e+09	INFO	controller.opensearchuserrolebinding	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchUserRoleBinding", "source": "kind source: *v1.OpensearchUserRoleBinding"}
> 1.6606480708474417e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.OpenSearchCluster"}
> 1.660648070847642e+09	INFO	controller.opensearchuser	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchUser", "source": "kind source: *v1.OpenSearchCluster"}
> 1.6606480708476424e+09	INFO	controller.opensearchuserrolebinding	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchUserRoleBinding", "source": "kind source: *v1.OpenSearchCluster"}
> 1.6606480708476527e+09	INFO	controller.opensearchuser	Starting Controller	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchUser"}
> 1.6606480708476562e+09	INFO	controller.opensearchuserrolebinding	Starting Controller	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchUserRoleBinding"}
> 1.660648070847673e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.Pod"}
> 1.6606480708476892e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.Secret"}
> 1.6606480708476994e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.ConfigMap"}
> 1.660648070847708e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.Service"}
> 1.660648070847736e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.Deployment"}
> 1.660648070847746e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.StatefulSet"}
> 1.6606480708477461e+09	INFO	controller.opensearchcluster	Starting Controller	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster"}
> W0816 11:07:50.854783       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:50.854822       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchRole: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:50.868590       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:50.868612       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUserRoleBinding: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:50.870149       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:50.870217       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUser: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:51.776898       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:51.776932       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUserRoleBinding: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:52.215575       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:52.215688       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUser: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:52.324137       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:52.324171       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchRole: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:54.350316       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:54.350363       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUser: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:54.351623       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:54.351653       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchRole: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:54.663603       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:54.663636       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUserRoleBinding: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:59.334585       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:59.334616       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUser: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:07:59.652854       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:07:59.652871       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUserRoleBinding: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:08:00.382839       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:08:00.382858       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchRole: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:08:06.566381       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:08:06.566414       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUser: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:08:06.988674       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:08:06.988717       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchRole: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:08:07.250944       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:08:07.250984       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUserRoleBinding: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:08:22.841977       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:08:22.842018       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUserRoleBinding: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:08:29.160502       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:08:29.160520       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUser: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:08:30.485528       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:08:30.485570       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchRole: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:09:08.102664       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:09:08.102701       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUser: failed to list *v1.OpensearchUser: opensearchusers.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchusers" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:09:13.136275       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:09:13.136325       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUserRoleBinding: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:09:20.969079       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:09:20.969113       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchRole: failed to list *v1.OpensearchRole: opensearchroles.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchroles" in API group "opensearch.opster.io" at the cluster scope
> W0816 11:09:47.427315       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> E0816 11:09:47.427347       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.OpensearchUserRoleBinding: failed to list *v1.OpensearchUserRoleBinding: opensearchuserrolebindings.opensearch.opster.io is forbidden: User "system:serviceaccount:opensearch-operator:opensearch-operator-controller-manager" cannot list resource "opensearchuserrolebindings" in API group "opensearch.opster.io" at the cluster scope
> 1.6606481908477452e+09	ERROR	controller.opensearchuser	Could not wait for Cache to sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchUser", "error": "failed to wait for opensearchuser caches to sync: timed out waiting for cache to be synced"}
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:208
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:234
> sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/runnable_group.go:218
> 1.6606481908478312e+09	INFO	Stopping and waiting for non leader election runnables
> 1.6606481908478434e+09	INFO	Stopping and waiting for leader election runnables
> 1.6606481908479605e+09	ERROR	controller.opensearchrole	Could not wait for Cache to sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchRole", "error": "failed to wait for opensearchrole caches to sync: timed out waiting for cache to be synced"}
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:208
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:234
> sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/runnable_group.go:218
> 1.6606481908479881e+09	ERROR	controller.opensearchuserrolebinding	Could not wait for Cache to sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpensearchUserRoleBinding", "error": "failed to wait for opensearchuserrolebinding caches to sync: timed out waiting for cache to be synced"}
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:208
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:234
> sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/runnable_group.go:218
> 1.6606481908480115e+09	ERROR	error received after stop sequence was engaged	{"error": "failed to wait for opensearchrole caches to sync: timed out waiting for cache to be synced"}
> sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/internal.go:541
> 1.6606481908480253e+09	ERROR	error received after stop sequence was engaged	{"error": "failed to wait for opensearchuserrolebinding caches to sync: timed out waiting for cache to be synced"}
> sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/internal.go:541
> 1.660648190848003e+09	ERROR	controller.opensearchcluster	Could not wait for Cache to sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "error": "failed to wait for opensearchcluster caches to sync: timed out waiting for cache to be synced"}
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:208
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:234
> sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/runnable_group.go:218
> 1.6606481908480515e+09	INFO	Stopping and waiting for caches
> 1.6606481908480752e+09	ERROR	error received after stop sequence was engaged	{"error": "failed to wait for opensearchcluster caches to sync: timed out waiting for cache to be synced"}
> sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/internal.go:541
> 1.6606481908482618e+09	INFO	Stopping and waiting for webhooks
> 1.6606481908482788e+09	INFO	Wait completed, proceeding to shutdown the manager
> 1.6606481908482988e+09	ERROR	setup	problem running manager	{"error": "failed to wait for opensearchuser caches to sync: timed out waiting for cache to be synced"}
> main.main
> 	/workspace/main.go:132
> runtime.main
> 	/usr/local/go/src/runtime/proc.go:255
> 1.6606481908483193e+09	ERROR	error received after stop sequence was engaged	{"error": "leader election lost"}
> sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/internal.go:541

**Comment by swoehrl-mw** [comment]
Hi @dobharweim. Can you please try again with the newest helm chart release (2.0.4)? The newest version should have the needed permissions.

**Comment by dobharweim** [comment]
Hi @swoehrl-mw yes I can confirm the fix in 2.0.4 resolves this issue. Thanks.
