### ISSUE TITLE
[meta] too many (stale) branches in this repo

### ISSUE THREAD

**Issue by rursprung** [Opster/opensearch-k8s-operator#257]
this repository currently has 42 branches, a lot of which are reported as stale by GH (mostly branches for PRs which have long since been merged), others which might still be moving a bit.

this makes it very hard for anyone looking at the repo to see which branches are relevant. please consider to move to a proper fork-based setup (see e.g. [the GitHub docs on contributing to projects](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)) where the upstream repo (this one here) only has important branches (main & release branches) and all development/feature branches are on personal forks (then it also doesn't matter if you forget to delete a branch as nobody but you will care about branches on your personal repo) and delete/move the other branches as needed.

**Comment by idanl21** [comment]
Thanks @rursprung, that's true. we will improve it .
