### ISSUE TITLE
Support topologySpreadConstraints

### ISSUE THREAD

**Issue by roelandvanbatenburg** [Opster/opensearch-k8s-operator#263]
Although Affinity is great, we tend to use [topologySpreadContraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) to better distribute our pods over regions, zones and nodes. The NodePools should support this.

**Comment by swoehrl-mw** [comment]
Was added with PR #264. I'm closing this issue as completed.
