### ISSUE TITLE
Cluster fails to recover after quorum of master/cluster_manager pods being deleted at the same time

### ISSUE THREAD

**Issue by swoehrl-mw** [Opster/opensearch-k8s-operator#289]
If for whatever reason (e.g. problem with the kubernetes cluster) all or a quorum of master pods are lost at the same time the opensearch cluster will not come back up again. Due to `podManagementPolicy: OrderedReady` kubernetes will launch the pods of the statefulset only one by one but as there is no quorum the first pod will never get healthy and therefore the other pods are never started.

Problem was first discussed in #266.

@prudhvigodithi @idanl21 We need to find a way for either the cluster to recover by itself or discover this situation in the operator and initiate some sort of recovery procedure.

**Comment by anubisg1** [comment]
i was bitted by this as well, thanks for saving me countless hours of head banging ..

**Comment by grzeg1** [comment]
Definitely the project is unusable - once there was a major failure (2 of 3 pods down) you can never recover.

**Comment by anubisg1** [comment]
> Did you try bumping node count from 3 to 4/5 before it fails?

That kind of defeats the purpose... We are talking about unexpected failure... If I had time to plan a cluster bump up in size this wouldn't be a problem

**Comment by ibexa-yuna** [comment]
I'm just saying that a bigger cluster is more resilient.
2 out of 3 is 66% drop in capacity, whilst 2 out of 5 is just 40% drop.

**Comment by anubisg1** [comment]
> I'm just saying that a bigger cluster is more resilient. 2 out of 3 is a 66% drop in capacity, whilst 2 out of 5 is just a 40% drop.

The issue is related to loss of quorum..

2 or more out of 3
3 or more out of 5
5 or more out of 7

Etc.. No matter how many, the bug is about quorum loss

**Comment by BlueBeN82** [comment]
I stumbled upon this as well. I was using Kubermatic to upgrade the Kubernetes Version from 1.24.8 to 1.24.9 which ended up in recreating all hosts of my cluster. It was done one by one. But they didn't wait for opensearch to be ready. I was able to recover from the situation using this strategy:
https://github.com/Opster/opensearch-k8s-operator/issues/266#issuecomment-1268499249

But currently implementation would cause opensearch downtime when I need to upgrade (or reform) my cluster.

**Comment by anubisg1** [comment]
is there any news on this bug? this issue togther with https://github.com/Opster/opensearch-k8s-operator/issues/400 are two main issues around stability and production readiness that together deserve a fix with release .

**Comment by swoehrl-mw** [comment]
> is there any news on this bug?

Hi @anubisg1. I have marked the PR for this issue as ready to review today. So hopefully we can merge the fix soon.

**Comment by anubisg1** [comment]
thank you!!! 

waiting for a bug fix release soon :)

**Comment by swoehrl-mw** [comment]
We just released version 2.2.1 which contains the fix for this bug.

**Comment by anubisg1** [comment]
> We just released version 2.2.1 which contains the fix for this bug.

you are the best! nothing else to say,, thank you !
