### ISSUE TITLE
Operator not creating an OpenSearch cluster in eks with Kubernetes 1.22

### ISSUE THREAD

**Issue by KeithMHughesRoteraAI** [Opster/opensearch-k8s-operator#295]
We have been using the operator on EKS using Kubernetes 1.21. We started scheduling our OpenSearch instances on Graviton machines (ARM) and they worked just fine.

We updated our nodes to Kubernetes v. 1.22, and the containers stopped working. They are dying in the init container, using a BusyBox that does not run on ARM.

![image](https://user-images.githubusercontent.com/85300499/191128164-e6979aa3-adc1-4d1e-b9c5-ef506dffe343.png)

The logs from the init container...

![image](https://user-images.githubusercontent.com/85300499/191128251-2ca4753e-ac8b-4200-a429-14c704e2c3bc.png)

Is there any way to specify the tag of the init container so we can specify the ARM version? Or, does your container registry support having multiple architectures for a given image tag?

**Comment by idanl21** [comment]
Hey @KeithMHughesRoteraAI, that's a wired issue, I built it again as a multi-arch image and pushed.

**Comment by KeithMHughesRoteraAI** [comment]
@idanl21 Still not working. Same result.

I wonder if something changed in 1.22 such that architecture resolution changes. For example, when I look at your registry, I see ARM as its own tag, and nothing about multiple architectures on the main tag.

![image](https://user-images.githubusercontent.com/85300499/191280461-91f39c3b-580a-4743-b37f-736f3ed5b7df.png)

whereas, when I look at Docker Hub for OpenSearch itself I see multiple architectures under the exact same tag.

![image](https://user-images.githubusercontent.com/85300499/191280804-21acc768-7261-4487-91b2-5fd58a9ed9ba.png)

BTW, I forgot to specify, I am using version 2.0.4 of the operator Helm chart, and v2.0.1 of the operator itself.

**Comment by swoehrl-mw** [comment]
Just two pitch in with my 2 cents: As far as I can tell both the busybox image and the opensearch image supply both architectures:
```bash
$ docker manifest inspect public.ecr.aws/opsterio/busybox:1.27.2-buildx | grep architecture
            "architecture": "arm64",
            "architecture": "amd64",
            "architecture": "arm",
$ docker manifest inspect opensearchproject/opensearch:2.3.0 | grep architecture
            "architecture": "amd64",
            "architecture": "arm64",
```

So sounds like a problem with archtecture resolution.

**Comment by KeithMHughesRoteraAI** [comment]
@swoehrl-mw Interesting. Thanks! Yeah, definitely architecture resolution, Just not sure how to address it.

**Comment by idanl21** [comment]
So, everything is fine here? Closing the issue, @KeithMHughesRoteraAI  if you have more questions you are welcome to open it again :)
