### ISSUE TITLE
OpenSearch Cluster CRD does not allow adding additionalConfig for bootstrap pod

### ISSUE THREAD

**Issue by plnordquist** [Opster/opensearch-k8s-operator#296]
In certain environments, changing the sysctl related to `vm.max_map_count` is not allowed.  In those environments, setting `node.store.allow_mmap` allows disabling memory mapped stores with a performance penalty.  I'm currently able to set this for the cluster with `spec.general.additionalConfig` but it doesn't seem like there is a way to alter the bootstrap pod's config.  This prevents the cluster from bootstrapping properly even though the main node starts.

**Comment by swoehrl-mw** [comment]
Hi @plnordquist . You are right that currently there is no way to supply additional configuration options to the bootstrap pod and I can see where this is needed. So maybe we need something like `spec.general.bootstrapNodeConfig`.

If you want to give this a go, PRs are always welcome.
