### ISSUE TITLE
Create configuration service

### ISSUE THREAD

**Issue by shahar35** [Opster/opensearch-k8s-operator#3]
This service is responsible for updating configuration that requires a rolling restart

**Comment by dbason** [comment]
@segalziv @idanl21 I'll pick this up and work on it.  I think in the first case it would be useful to create a framework for scheduling rolling restarts, and then we can look at the configuration.

Do we have any ideas about the configurations that we want to change here?  I've tried looking for a well defined list of static opensearch settings (those which require a restart) but I haven't been able to find this.  Would this largely be related to modifying the zone attributes for a node pools, or changing a node pools roles?

**Comment by segalziv** [comment]
From what I can tell, everything/most of what exist in OpenSearch.yaml file are configurations that changing them require a restart, as OpenSearch doesn't watch that file dynamically.
That can be zone attributes, thread pools configs and many others.

**Comment by dbason** [comment]
That make sense.  I think the best approach is going to be to allow arbitrary additional configs in the genenal config section (these would be cluster wide) and per node pool.  We can then gather these up when we build the opensearch.yaml, and schedule a restart when the generated content changes.
