### ISSUE TITLE
Opensearch Dashboards - Probes failing when not running on root url

### ISSUE THREAD

**Issue by aschi1** [Opster/opensearch-k8s-operator#309]
Hello there,
We are trying to deploy OD via the operator and we would like to have it running with base path "/logs". We achieved this via the operator without issues but the problem we have is that the probes are not aware of this change and are trying to access old endpoints without "/logs"

Our settings to deploy OD
```
  dashboards:
    enable: true
    version: 2.3.0
    replicas: 1
    additionalConfig:
      server.basePath: "/logs"
      server.rewriteBasePath: "true"
    ...
```

Probe failures from kubernetes
```
  Warning  Unhealthy  90s                kubelet            Startup probe failed: Get "https://IP:5601/api/reporting/stats": dial tcp IP:5601: connect: connection refused
  Warning  Unhealthy  65s                kubelet            Startup probe failed: Get "https://IP:5601/api/reporting/stats": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  10s (x3 over 50s)  kubelet            Startup probe failed: HTTP probe failed with statuscode: 404
```

I am able to log in to OD via browser without issues but after time Kubernetes restarts the pod because of probes failing. Are we overlooking something or is this a limitation of the operator as of now?

**Comment by swoehrl-mw** [comment]
Hi @aschi1. The path for the health probe is hardcoded in the operator. As such changing the basepath is currently not possible.
But I think this is a good feature that should be added to the operator (ideally we add a field to the CRD to configure a basepath and the operator automatically adds the needed configuration statements). I'll mark this issue as an enhancement request.

**Comment by aschi1** [comment]
Thank you for your response and your help :+1:
