### ISSUE TITLE
Do not hardcode livenessProbe path

### ISSUE THREAD

**Issue by Nirvandil** [Opster/opensearch-k8s-operator#329]
Hello.
OpenSearch-Dashboards supports [server.basePath](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/33aed0a6bdba070a37bc3002f4a86a81a0150677/config/opensearch_dashboards.yml#L13) environment variable for working behind reverse proxy. When selected, it's api uri prefixed with this value. We need this feature for our setup.
But accidently operator [hardcodes livenessProbe path](https://github.com/Opster/opensearch-k8s-operator/blob/8b9ab34fcdb6922c213be2d6109980d92552b5ab/opensearch-operator/pkg/builders/dashboards.go#L86), leading to 404 response leading to not getting ready for dashboard pod. 
Unfortunately, even kubectl edit does not work - operator rewrites it on his own. 
So somewhere should be either basePath param or ability to pick up this from dashboard's env.

**Comment by swoehrl-mw** [comment]
There is already an open issue for this (#309). Closing this one as duplicate.
