### ISSUE TITLE
Bump controller-gen

### ISSUE THREAD

**Issue by FactorT** [Opster/opensearch-k8s-operator#330]
- Bump controller-gen to v0.10.0 for supporting latest kubernetes version
- Remove crd options trivialVersions and preserveUnknownFields since they are no longer supported in later version of controller-gen after this commit https://github.com/kubernetes-sigs/controller-tools/commit/09f1952580d4e40a3aab8b1c4f6bfc8de3ae0b0b

**Comment by idanl21** [comment]
Fixed with the PR:
https://github.com/Opster/opensearch-k8s-operator/pull/331
will merge soon
