### ISSUE TITLE
How to recover from cluster failure

### ISSUE THREAD

**Issue by CodeGlitcher** [Opster/opensearch-k8s-operator#336]
Hi

We are trying somethings out and trying to figure out how we need to use the operator, what is it can and cannot do.
In our setup we have 3 opensearch nodes with the roles
        - "data"
        - "cluster_manager"

when all 3 nodes are down kuberentes cannot bring them up aggain.
(we used kubelctl delete --all to simulate this.)
When kuberentes restarts the first pod it is try to connect with the other master before reporting ready.
But Kubernetes waits for de first node to be ready before starting the next pod.

How do we recover from this?

In production we dont expect someone to delete all pods, but it has happend before that during a onpremise upgrade or some mistake, a full storage the kubernetes cluster was shutdown or left in a broken state.
So we want a way to recover from this.

**Comment by swoehrl-mw** [comment]
Hi @CodeGlitcher. This is a known problem and there is an open issue for it (#289).
Currently you would need to use a little hack:
* Stop the operator
* Delete the statefulset with `--cascade=orphan`
* Recreate the statefulset but set `podManagementPolicy` to `Parallel`, that should get all pods up at the same time
* After the cluster is up, delete the statefulset again (again with orphan to keep the pods)
* Restart the operator so it recreates the correct statefulset

Closing this issue as a duplicate.
