### ISSUE TITLE
Document the usage of   smartScaler: true

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#339]
I have been going through examples and did not find any docs describing the usage of below. 

Can someone explain here.

```
  confMgmt:
    smartScaler: true
```

**Comment by swoehrl-mw** [comment]
@idanl21 I think you did most of the early implementation of the scaler, can you take this?

**Comment by segalziv** [comment]
Hi @KannappanSomu , 
Good question, indeed we need to add this description to the documentation. 
Basically, smartScaler is a configuration that tells the operator what logic to use when scaling down data nodes. 
if smartScaler: true the operator would drain the data nodes before removing them on scale down.
if smartScaler: false the operator would remove data nodes in scale down without draining them in advance.

**Comment by KannappanSomu** [comment]
Hi @segalziv ,

By draining the data node, you mean move the allocation of shards from one node to other?

**Comment by segalziv** [comment]
Drain means to exclude that node in shards allocation, causing the cluster manager/master to move the shards away from the node to other nodes where allocation is allowed. On this case of drain the operator would wait until the number of shards in the node is 0 before removing it.

**Comment by KannappanSomu** [comment]
thanks for explaining.
