### ISSUE TITLE
Manually created ingress is not working, redirecting.

### ISSUE THREAD

**Issue by jonathon2nd** [Opster/opensearch-k8s-operator#342]
Hello! 

I was making progress and wanted to expose the dashboard and master node API for testing. I looked at https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#dashboards-http, and setup an ingress used by traefik. 

I had one issue where traefik was insisting the service was http, and it was getting that from the service
![image](https://user-images.githubusercontent.com/52681917/199599627-f066282d-e5f3-46fe-9277-d03bbf396848.png)

It was getting that from the port name, and trying to change it to https causes the operator to overwrite it
![image](https://user-images.githubusercontent.com/52681917/199599076-ef582f7f-6920-4440-a9ab-d6e15662995d.png)

No big deal, made a copy service with name `https`, but now I am getting a redirect failure.
I enter Request URL: https://labs-dashboard.example.com/, and get Status Code: 302 
I then land on this url https://labs-dashboard.example.com/app/login?nextUrl=%2F with a 404

This is going through Cloudflare, but the results are the same with or without their proxy.

I would think that the dashboard and opensearch would need to be aware of this hostname `labs-dashboard.example` for this very reason, but I am not fining where that could be set.

Could I be pointed in the right direction? Thanks!

**Comment by idanl21** [comment]
Hey @jonathon2nd, im not familiar with Traefik, but i tried with Ngnix ingress and all works fine. also with kubeForwarder.

**Comment by jonathon2nd** [comment]
I was dumb lol
During my testing I changed `pathType`, and it needs to be `Prefix`. Once that was changed back it was working.

**Comment by jonathon2nd** [comment]
Here is a redacted file for how I got it setup.
[opensearch-ingress.txt](https://github.com/Opster/opensearch-k8s-operator/files/9933428/opensearch-ingress.txt)

You can see I had to create extra services with the https portname
