### ISSUE TITLE
Wrong apiGroup in helm chart manager role 

### ISSUE THREAD

**Issue by vanveele** [Opster/opensearch-k8s-operator#352]
The helm chart includes a role for the operator where one permission appears to target the wrong apiGroup ("opensearch.opster.io" rather than "")

https://github.com/Opster/opensearch-k8s-operator/blob/c95a450504a4ecceaf9788f0a39615e88ef5f6bf/charts/opensearch-operator/templates/opensearch-operator-manager-role-cr.yaml#L105

Comparing to the same definition in the example role outside of the helm chart seems to confirm the issue:

https://github.com/Opster/opensearch-k8s-operator/blob/0ac8ee6733830568ea61f29527354d50889ea747/opensearch-operator/config/rbac/role.yaml#L57

In general, the helm chart role lags behind the non-helm example by a few commits. Should these changes also get brought into the helm chart?

**Comment by swoehrl-mw** [comment]
Hi @vanveele. Thank you for reporting this. You are right, that is the wrong apiGroup. And yes, looks like we forgot to keep the role definition in the helm chart up-to-date.

**Comment by idanl21** [comment]
Solved on https://github.com/Opster/opensearch-k8s-operator/pull/357#pullrequestreview-1174064137
