### ISSUE TITLE
Nodeselector for bootstrap pod

### ISSUE THREAD

**Issue by drmiru** [Opster/opensearch-k8s-operator#360]
I can force masters, coordinators and data nodes to be scheduled on a certain node pool or node using the **nodeSelector** field. However, this seems not possible for the bootstrap pod.
version used: 2.1.1

Any hints or is it just not supported yet?

**Comment by swoehrl-mw** [comment]
Hi @drmiru. `nodeSelector` is available for the bootstrap pod and it works the same as for nodepools. Please see the CRD reference: https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/crd.md#--bootstrap

**Comment by drmiru** [comment]
> Hi @drmiru. `nodeSelector` is available for the bootstrap pod and it works the same as for nodepools. Please see the CRD reference: https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/crd.md#--bootstrap

@swoehrl-mw  Thanks for the hint! Works.
