### ISSUE TITLE
When can we expect a new helm release? 

### ISSUE THREAD

**Issue by andloh** [Opster/opensearch-k8s-operator#364]
Would really like to have some features that are in `main` right now into a new release.

Thanks for the work being done on this operator! :D

**Comment by swoehrl-mw** [comment]
Hi @andloh. Great to hear you're enjoying the operator.
There is currently no planned date for the next release, but I think it will be some weeks as there are a number of open issues/PRs/features that should get included in it.

In the meantime, if you want to live on the edge so to speak, you can always run the operator from the main branch:
* Check out the repo
* Build the docker image: `cd opensearch-operator; IMG=<your-registry>/opensearch-controller:<your-tag> make docker-build docker-push`
* Deploy the operator: `helm install opensearch-operator ./charts/opensearch-operator --set manager.image.repository=<your-registry>/opensearch-controller --set manager.image.tag=<your-tag>`
