### ISSUE TITLE
Allow setting of podSecurityContext on cluster pods

### ISSUE THREAD

**Issue by michael-datareply** [Opster/opensearch-k8s-operator#373]
Currently the OpensearchCluster CRD doesn't support setting a securityContext on the cluster pods. This currently prevents us from using it.

**Comment by swoehrl-mw** [comment]
Hi @michael-datareply. I believe this is something that can be added to the operator.
If you have the time, PRs are always welcome.

**Comment by saketmht** [comment]
Hi @swoehrl-mw . I can raise a PR for this. Can we have something similar to the Opensearch helm for this?
In the Opensearch helm, there are two fields:
```
podSecurityContext:
 ...

securityContext:
 ...
```
The podSecurityContext maps to the cluster pod's security context and the securityContext maps to the security context of the main OS container. 
Ref - https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L286
https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/templates/statefulset.yaml#L71

So we can have these similar fields in the CRD. `spec.general.podSecurityContext` and `spec.general.SecurityContext` as type map[string]string which we can unmarshal to a `podSecurityContext` and `securityContext` objects and add it to the sts. We can add similar fields for the dashboard as well.

**Comment by swoehrl-mw** [comment]
Hi @saketmht . PRs are always welcome.
Please do not use a simple map, instead reference the appropriate objects from the kubernetes API (`PodSecurityContext` and `SecurityContext`). That way there is no need to parse anything and we get automatic syntax validation on the fields. This same pattern is already in place for several fields in the CRD.

**Comment by swoehrl-mw** [comment]
Feature has been implemented with PR #456 and will be available with the next release. Closing this issue as completed.
