### ISSUE TITLE
Setup APM tracing and port

### ISSUE THREAD

**Issue by jonathon2nd** [Opster/opensearch-k8s-operator#375]
Hello!

I am attempting to test out tracing using opensearch. I was first attempting to test for [traefik](https://doc.traefik.io/traefik/observability/tracing/elastic/). I am finding references:
https://github.com/opensearch-project/observability#trace-analytics
https://opensearch.org/docs/latest/observability-plugin/trace/index/
But not really seeing how to config things
![image](https://user-images.githubusercontent.com/52681917/204599307-960fc5fb-aa86-476c-b45e-c9ef6f235c35.png)

If I could be directed to config/doc that would be awesome.

**Comment by swoehrl-mw** [comment]
Hi @jonathon2nd. Setting up and configuring trace analytics is out of the scope of this operator, please see the normal opensearch documentation (that you already linked to) on how to set this up.

At this time you will not be able to do trace analytics with an opensearch cluster setup via the operator as it currently does not support installing dashboards plugins.  I've opened a feature request for that (#378). If you want to use the plugin in the mean time you will need to build and provide your own dashboards docker image.
