### ISSUE TITLE
Next Release Request

### ISSUE THREAD

**Issue by cfBrianMiller** [Opster/opensearch-k8s-operator#376]
Hello,

When is the next release of the main branch scheduled for? The current build uses golang 1.17 which has several high severity CVEs associated. The main branch has upgraded to 1.19 with this commit dda6f2d013ed63553e265415084adf14d0a59635. Providing an updated release will resolve these vulnerabilities.

Thank you

**Comment by swoehrl-mw** [comment]
Hi @cfBrianMiller. We are planning to release a 2.2.0 that includes the go 1.19 upgrade in the next few days.

**Comment by idanl21** [comment]
Like Sebastian said, the next release is including go 1.19 upgrade, it will release probably next week. Closing the issue for now
