### ISSUE TITLE
[question / feature request] - allow to pass env variables to opensearch manifest (additional config) opensearch-dashboard

### ISSUE THREAD

**Issue by anubisg1** [Opster/opensearch-k8s-operator#379]
current manifest allows to provide opensearch dashboard configuration via "additionalConfig" 

This is great, but as discussed already in other issues here: https://github.com/Opster/opensearch-k8s-operator/issues/284 and here: https://github.com/Opster/opensearch-k8s-operator/issues/235  what is done today isn't enough.

Another example of this shortcoming (and the reason why i am opening another issue) is related to the dashboard config for SSO,
When configuring Single Sign On, and specifically OpenID the following config is requested:

```
opensearch_security.openid.client_id: "xxxxxx"
opensearch_security.openid.client_secret: "xxxxxx"
opensearch_security.openid.base_redirect_url: "https://xxxxx.com"
opensearch_security.openid.connect_url: "https://xxxxx"
```

At the very least the field `opensearch_security.openid.client_secret` is sensitive information  that should not be stored in clear text

A possible way to address the issue is by allowing the user to pass a "podTemplate" that the operator would then merge with the statefulsets/deployments. 
The additional benefit is that everything not supported directly by the operator could be passed as a template, and for example, address issues like https://github.com/Opster/opensearch-k8s-operator/issues/275  

as for the question .. how can i pass today senstive data? is it even possible?

**Comment by swoehrl-mw** [comment]
Hi @anubisg1 

There is an existing feature request (#270) to allow pod templates. 

> as for the question .. how can i pass today senstive data? is it even possible?

This is possible today using variable substitution in the config, please see #350.

**Comment by swoehrl-mw** [comment]
> Great, so this solves my immediate problem... then it needs to be documented.. do you want to close this as duplicate then?

Good to hear. I'm closing this ticket and will make a note to add a paragraph about this to the userguide.
