### ISSUE TITLE
The operator should create a Pod Disruption Budget

### ISSUE THREAD

**Issue by simonmacklin** [Opster/opensearch-k8s-operator#391]
The operator does not create a pod distribution budget to ensure the service interruption is limited when its pods need to be rescheduled such as upgrades or routine maintenance.

**Comment by swoehrl-mw** [comment]
Hi @simonmacklin. 
That is a good suggestion and a good idea to have. I'll mark this issue as enhancement request.

**Comment by simonmacklin** [comment]
Happy to take this work on when I get some free time if no one does this in the mean time

**Comment by stdmje** [comment]
This is high priority IMHO.

**Comment by stdmje** [comment]
Also it will be nice to add custom labels to the bootstrap pod and create an additional pod disruption budget for it so when the cluster is bootstrapping that pod can't be evicted because it will cause bootstrap to fail.
