### ISSUE TITLE
additionalConfig doesnt allow to add multiple flattened keys staring with same path "cluster.routing.allocation" for example

### ISSUE THREAD

**Issue by val16384** [Opster/opensearch-k8s-operator#398]
Declaration of cluster with following code

```
      additionalConfig: 
        discovery.seed_hosts: my-cluster-masters-0
        cluster.initial_master_nodes': my-cluster-masters-0
        cluster.routing.allocation.disk.threshold_enabled: true
        cluster.routing.allocation.disk.watermark.flood_stage: 5gb
        cluster.routing.allocation.disk.watermark.low: 30gb
        cluster.routing.allocation.disk.watermark.high: 20gb
```

throw  the error  when applying with kubectl apply -f 

`error: error parsing my-cluster.yml: error converting YAML to JSON: yaml: line 45: could not find expected ':'`

This is not valid YAML (  "Implicit map keys need to be followed by map values")

Is there any way to work around this issue ?

**Comment by val16384** [comment]
May be additionalConfig  should be decaled as array  not map ?

**Comment by swoehrl-mw** [comment]
Hi @val16384. I believe you have a lone single quote `'` in the line with `cluster.initial_master_nodes` that is mucking up your YAML. The operator should be able to handle what you want to specify.
Side note: Please do not specify `discovery.seed_hosts` or `cluster.initial_master_nodes`. These are calculated and set by the operator.

**Comment by val16384** [comment]
@swoehrl-mw 
You are right. Its works .  
Thank you.
My mistake
Also delimiters between keys and  values  in my config wasnt space but some  special characters looked likes spaces(
