### ISSUE TITLE
latest version 2.1.1 has wrong crds?

### ISSUE THREAD

**Issue by christiancarle-bakery** [Opster/opensearch-k8s-operator#401]
What I can see, [OpensearchUserRoleBinding-crd.yaml](https://github.com/Opster/opensearch-k8s-operator/blob/v2.1.1/charts/opensearch-operator/templates/OpensearchUserRoleBinding-crd.yaml) is not the same crd as in main branch. Is this intentional or just a misstake?

**Comment by idanl21** [comment]
I believe this is a mistake, cause they should be the same
@swoehrl-mw @lieberlois

**Comment by lieberlois** [comment]
The CI file `.github/workflows/prepare-release.yaml` contains the logic to copy the according crd files into the helm chart:

```sh
cp opensearch-operator/config/crd/bases/opensearch.opster.io_opensearchclusters.yaml charts/opensearch-operator/templates/opensearchclusters.opensearch.opster.io-crd.yaml
cp opensearch-operator/config/crd/bases/opensearch.opster.io_opensearchroles.yaml charts/opensearch-operator/templates/OpensearchRole-crd.yaml
cp opensearch-operator/config/crd/bases/opensearch.opster.io_opensearchuserrolebindings.yaml charts/opensearch-operator/templates/OpensearchUserRoleBinding-crd.yaml
cp opensearch-operator/config/crd/bases/opensearch.opster.io_opensearchusers.yaml charts/opensearch-operator/templates/OpensearchUser-crd.yaml
```

Maybe the release was done without the pipeline? I'm not entirely sure since I don't have influence on the release cycle
