### ISSUE TITLE
Bootstrap is failing due to low virtual memmory limit

### ISSUE THREAD

**Issue by masifeddress** [Opster/opensearch-k8s-operator#402]
Hi Geeks,

I was trying to install opensearch cluster using operator. But I am facing following issue in bootstrap. So other pods are in pending state. I have two nodes cluster on GKE and free resources are also limited.

`max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`

Please guide.

**Comment by iNode** [comment]
You can try to use `setVMMaxMapCount` as it's mentioned in [CRD reference](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/crd.md) and you can see in the [source code](https://github.com/Opster/opensearch-k8s-operator/blob/a5f01b6248c94bc123f96868456de2e88774ab4b/opensearch-operator/pkg/builders/cluster.go#L460) what it does. 

Sample part of cluster config:
```yaml
spec:
  general:
    # some lines omited
    setVMMaxMapCount: true
```

**Comment by idanl21** [comment]
Hey @masifeddress?
is it helped you?

**Comment by masifeddress** [comment]
No difficult to understand. I had multiple nodes on GKE and it was difficult to update sysctl one by one
Thanks God I found this solution.

https://gist.github.com/thbkrkr/bc12a3457fd0f71c5a2106b11ce8801e

**Comment by idanl21** [comment]
Ho so you added to update the sysctl on the GKE node and also under the Opensearch cluster nodes.
ok got it, closing that issue :)
