### ISSUE TITLE
Init container resource limits

### ISSUE THREAD

**Issue by srekkas** [Opster/opensearch-k8s-operator#407]
Hello,

    Our k8s implementation require resource limits for all containers. Without limits they wont create.
How to set resource limits for init container?

**Comment by swoehrl-mw** [comment]
Hi @srekkas.
Unfortunately it is currently not possible to configure resources for the init containers. But I can see the benefits.

I'll mark this issue as a feature request. If you have the time and energy, PRs are always welcome.

**Comment by srekkas** [comment]
Hello

  Thank you for reply.
I found out that you can set default resource limits, which then automatically applied. So its nod needed anymore for me.

https://kubernetes.io/docs/concepts/policy/limit-range/

**Comment by kfox1111** [comment]
Please reopen. Thats an ok workaround for some folks, but not others. It really should be fixed properly.

**Comment by danielba32** [comment]
add k8s implementation to support resources limits for init container -
[](https://github.com/Opster/opensearch-k8s-operator/pull/476)

**Comment by danielba32** [comment]
add k8s implementation to support resources limits for init [container](https://github.com/Opster/opensearch-k8s-operator/pull/476)
