### ISSUE TITLE
Typo in User Guide/Quickstart section

### ISSUE THREAD

**Issue by FlappiTomic** [Opster/opensearch-k8s-operator#412]
Hi!

I am following the quickstart guide and kubectl apply it. https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#quickstart

I am getting an error: `OpenSearchCluster in version "v1" cannot be handled as a OpenSearchCluster: strict decoding error: unknown field "spec.nodePools[0].NodeSelector"`.

I initially thought the sample is out of date or the APIs getting updated, but actually there is a typo in the doc. There is `spec.nodePools[].NodeSelector`: `NodeSelector` should be `nodeSelector`.

Not critical but it can save first time user like me quite sometime to figure if something is incorrectly configured.

Thanks.

**Comment by swoehrl-mw** [comment]
Hi @FlappiTomic. Thanks for reporting this. Yes, this is indeed just a typo, but as you said it's a bad one.
