### ISSUE TITLE
Plugins not getting installed

### ISSUE THREAD

**Issue by danielbichuetti** [Opster/opensearch-k8s-operator#414]
I tried to find something related to latest release, but I couldn't. On a brand new cluster deployment, repository-s3 and repository-azure are not being installed, even being listed at pluginsList.

Has anyone else faced this issue?

**Comment by ashutoshkumaranshu** [comment]
I am also facing the same issue ? How you @danielbichuetti  fixed this issue ? Could you please guide me ?
