### ISSUE TITLE
update compatability list

### ISSUE THREAD

**Issue by rhys-evans** [Opster/opensearch-k8s-operator#417]
Hi

The list here (https://github.com/Opster/opensearch-k8s-operator#compatibility) does not list the 2.2 release and its compatible opensearch versions

Thanks

**Comment by swoehrl-mw** [comment]
Hi @rhys-evans, thanks for reporting this, we forgot to update the matrix after the last release. I've just done that.

**Comment by rhys-evans** [comment]
Thank you
