### ISSUE TITLE
Setting podSecurityContext for the cluster pods

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#421]
Currently there is not explicit securityContext defined for the OS and OSD cluster pods created by the operator. Also there seems to be no way to set the same through the OpenSearchCluster CRD which prevents us from setting it ourselves. I think it would be good to have a way that allows users to set the securityContext for the pods. I can submit a PR for this if this seems like a good idea.

**Comment by swoehrl-mw** [comment]
Hi @saketmht. There is already an existing feature request for this: #373.
I'm closing this one as a duplicate.
