### ISSUE TITLE
[OMC] Helm Chart - tolerations & nodeSelector are missing

### ISSUE THREAD

**Issue by Amos-85** [Opster/opensearch-k8s-operator#425]
I'm exploring opensearch operator and part of it is about opensearch management console.
The latest version of OMC [v1.9.5](https://artifacthub.io/packages/helm/opster-omc/omc) include `tolerations` & `nodeSelector` in `values.yaml` but they are missing from `deployment.yaml` template.

I'm not sure this is the right place to raise this issue but I haven't found Opster OMC git repository helm chart in the github namespace.

I'll be glad to contribute if you can share the OMC chart.

**Comment by idanl21** [comment]
Hey @Amos-85 :)
Im happy to see that you are using the OMC!
You are absolutely right, it is did not exist on the template.
We will fix that and release a new version as soon as possible.
By the way, i would to talk with you about the OMC, get your opinion and see what is your experience with the product, i you want you can send me an email on idan@opster.com :) 

Thanks and have a great day !

**Comment by Amos-85** [comment]
Thanks @idanl21 for the response.
Actually I haven't succeeded to install OMC because of those limitations I mentinoed :).

Hope you will fix it soon.

**Comment by idanl21** [comment]
Can you send me the logs for it? cause it shouldn’t effect the installation (unleash you need to deploy with tolerations & nodeSelector ?

**Comment by Amos-85** [comment]
Hi @idanl21,
In my case,
I must use tolerations & nodeSelector / node affinity rules, I'll prefer to wait for the next helm chart release of OMC.
Is Opster will share the OCM chart for contribution ?
