### ISSUE TITLE
JVM allocation on NodePools

### ISSUE THREAD

**Issue by idanl21** [Opster/opensearch-k8s-operator#426]
As i can see, we always declaring the JVM to be "-Xmx512M -Xms512M" unless the client as declared else inside of the CRD (nodepool.jvm) .
That's means that if a client is resizing the RAM allocation inside of the NodePool, if he didnt updated the JVM as well, it will still be hardcoded "-Xmx512M -Xms512M".
I think that we need to add a logic in the code that takes the request and limit of the MEM inside of a node pool, divide it by 2 (or other calculation that we will agree on) and put that value under the JVM opts.

**Comment by iNode** [comment]
This looks similar to what was discussed in #171 in context of RAM percentage. Can it (RAM percentage configuration) be used there on pod side by default to avoid extra actions on operator side?
