### ISSUE TITLE
OpensearchDashboards plugins install not working for more than one plugin

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#433]
Issue - 
Specifying more than one plugin in the pluginsList for the Dashboards in the CR only installs the first plugin and not the rest.

Configuration applied - 
```
dashboards:
  pluginsList:
    - securityDashboards
    - reportsDashboards
```

```
dashboards:
  pluginsList: [securityDashboards, reportsDashboards]
```
Only the securityDashboards plugin (using an image without the securityDashboards plugin) is installed and not the reportsDashboards
The command in the deployment looks like
`./bin/opensearch-dashboards-plugin install 'securityDashboards' 'reportsDashboards'` 
Tried this same command in a standalone OSD pod and the plugin install basically ignores the second plugin. And OSD-plugin install doesn't support batch mode either. So, the command should probably be built as 
`./bin/opensearch-dashboards-plugin install 'reportsDashboards' && ./bin/opensearch-dashboards-plugin install 'securityDashboards' && ...`

**Comment by swoehrl-mw** [comment]
Hi @saketmht. Thanks for reporting this. Looks like we'll have to install the plugins one at-a-time as you suggested.
