### ISSUE TITLE
TLS handshake error in opensearch-operator-controller-manager with 2-node cluster

### ISSUE THREAD

**Issue by Dougems** [Opster/opensearch-k8s-operator#437]
**Environment**

I am running a 2-node MicroK8s cluster on Ubuntu VMs hosted in VMWare.

```
$ snap info microk8s | grep installed
installed:               v1.26.1                    (4595) 176MB classic

$ mk get nodes -o wide
NAME           STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
ub-nodedev     Ready    <none>   17d   v1.26.1   10.140.70.4     <none>        Ubuntu 22.04.1 LTS   5.15.0-60-generic   containerd://1.6.8
ub-nodedev1    Ready    <none>   25h   v1.26.1   10.140.69.217   <none>        Ubuntu 22.04.1 LTS   5.15.0-60-generic   containerd://1.6.8
```

- ub-nodedev is the master node from which I run all "microk8s kubectl " commands (aliased to "mk").
- ub-nodedev1 is a worker node.

This is for development purposes. I know this does not represent a production topology. I am able to deploy pods, daemonsets, etc. using kubectl on all nodes, and based on my usage the cluster appears to be "working".

**What I did**

I followed the instructions to deploy the operator. I did have to manually add the https://opensearch-project.github.io/helm-charts/ repo:

```
$ mh repo add opensearch-operator https://opster.github.io/opensearch-k8s-operator/
"opensearch-operator" has been added to your repositories

$ mh repo list | grep open
opensearch-operator             https://opster.github.io/opensearch-k8s-operator/

$ mh repo add opensearch https://opensearch-project.github.io/helm-charts/
"opensearch" has been added to your repositories

$ mh repo list | grep open
opensearch-operator             https://opster.github.io/opensearch-k8s-operator/
opensearch                      https://opensearch-project.github.io/helm-charts/
```
I then installed the operator. I also tried this a second time with "--version=2.2.1" with identical results.
```
$ mh install my-opensearch-operator opensearch-operator/opensearch-operator
NAME: my-opensearch-operator
LAST DEPLOYED: Fri Feb 17 01:32:54 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

The first sign of trouble is that there's no namespace with "open", though the NAMESPACE shown in the install above is "default":

```
$ mk get ns | grep open
(nothing)
```

The log for the opensearch-operator-controller-manager shows continuously growing list of TLS handshake errors which appear to originate from inbound (?) requests from the worker node:

```
$ mk get pods -A | grep open
opensearch-operator-controller-manager-8568955f5c-5jrbm   2/2     Running   0              35s

$ mk logs opensearch-operator-controller-manager-8568955f5c-5jrbm
Defaulted container "kube-rbac-proxy" out of: kube-rbac-proxy, operator-controller-manager
I0217 01:33:00.761095       1 main.go:190] Valid token audiences:
I0217 01:33:00.858173       1 main.go:262] Generating self signed cert as no cert is provided
I0217 01:33:19.559635       1 main.go:311] Starting TCP socket on 0.0.0.0:8443
I0217 01:33:19.560540       1 main.go:318] Listening securely on 0.0.0.0:8443
2023/02/17 01:33:27 http: TLS handshake error from 10.140.69.217:52178: EOF
2023/02/17 01:33:27 http: TLS handshake error from 10.140.69.217:52194: EOF
2023/02/17 01:33:42 http: TLS handshake error from 10.140.69.217:44614: EOF
2023/02/17 01:33:42 http: TLS handshake error from 10.140.69.217:44624: EOF
2023/02/17 01:33:57 http: TLS handshake error from 10.140.69.217:52250: EOF
2023/02/17 01:33:57 http: TLS handshake error from 10.140.69.217:52262: EOF
```

It's not clear to me what's happening here. Perhaps this is harmless?

The CRD elements are present:

```
$ mk get crd | grep opens
opensearchusers.opensearch.opster.io                  2023-02-17T01:32:56Z
opensearchuserrolebindings.opensearch.opster.io       2023-02-17T01:32:56Z
opensearchroles.opensearch.opster.io                  2023-02-17T01:32:56Z
opensearchclusters.opensearch.opster.io               2023-02-17T01:32:56Z
```

The install instructions (at least the video) don't mention anything with regard TLS or setting up certificates prior/during the _install_.

I may need to apologize in advance as I'm not even sure if this is an issue with the operator, or if perhaps certificates needed to be installed on the Ubuntu nodes themselves as part of the MicroK8s install.

Essentially any guidance on what to try next would be appreciated.

**Comment by Dougems** [comment]
Closing as the TLS handshake error doesn't seem to prevent me from actually attempting to create a OS cluster. It's not quite working, but probably better explored in a separate ticket.

**Comment by kinseii** [comment]
The same problem
