### ISSUE TITLE
Faulty logic for comparing existing diskSize and required diskSize

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#441]
Issue - The current logic which checks whether the existing diskSize is equal to the required diskSize(from the CR) is checking the string representation of the sizes which is not a correct comparison of resource quantities.

```
existingDisk := existing.Spec.VolumeClaimTemplates[0].Spec.Resources.Requests.Storage().String()
r.logger.Info("The existing statefulset VolumeClaimTemplate disk size is: " + existingDisk)
r.logger.Info("The cluster definition nodePool disk size is: " + nodePool.DiskSize)
if existingDisk == nodePool.DiskSize { # both are strings
...
} else {
...
}
```

This logic fails when the units are swapped (eg- from G to Gi or vice-versa) even if the quantity itself is equal as it would compare the string representation i.e. `5 GiB == 5.36870912 GB` which is equal but with present logic it would be false. 

Similarly, if diskSize is defined as `5.36870912G` in the CR, then the operator is stuck reconciling forever as the resource.ParseQuatity (used to parse quantity during resizing and creation of pvc)would return `5368709120` and nodePool.DiskSize would be `5.36870912G` so they would never be equal.

Proposed Solution :- 
The k8s api to compare resources should be used
```
existingDisk := existing.Spec.VolumeClaimTemplates[0].Spec.Resources.Requests.Storage().Equal(resource.MustParse(nodePool.DiskSize))
```

**Comment by swoehrl-mw** [comment]
Hi @saketmht. You've discovered an interesting edge case. I doubt many would run into this, but you are right, we should properly compare the sizes.

**Comment by prudhvigodithi** [comment]
Hey @saketmht thanks for the bringing this up, I have added description on this [created feature issue](https://github.com/Opster/opensearch-k8s-operator/issues/88#issue-1186707774) that describes some size units.
The Operator even though the disk size is inferred as equal while comparing, the PVC scaling should be fired, whereas in the backend the cloud provider calling the scaling API's should not fail even though the scaling fired for the same size (I remember I have tested this with AWS while implementing this disksize reconciler). However as you proposed  k8s api to compare resources should be used, but this should not break making the operator stuck. Can you share the Initial number used in CR and the size you are trying to scale? I will try to replicate it.
Thank you
