### ISSUE TITLE
Feature: Allow `search` node role

### ISSUE THREAD

**Issue by rhysxevans** [Opster/opensearch-k8s-operator#449]
Hi

To allow the usage of the experimental feats Searchable Snapshots , we need to assign our nodes the `search` role  as per https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot/ 

I am assuming it is just updating this list https://github.com/Opster/opensearch-k8s-operator/blob/4edd47a61f05e2a3b2e38d826f9fb5ca33e55f1f/opensearch-operator/pkg/builders/cluster.go#L46 to support that functionality. However I may be wrong

Thanks

**Comment by idanl21** [comment]
PR waiting for review and merge, closing issue
