### ISSUE TITLE
Change registry

### ISSUE THREAD

**Issue by Paramoshka** [Opster/opensearch-k8s-operator#453]
If I understand correctly the old image repository will become unavailable in a few months please fix values.yaml
https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
opensearch-operator/templates/opensearch-operator-controller-manager-deployment.yaml

old image link: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0

**Comment by idanl21** [comment]
Thanks its improvement that we have to do!
if you want you can upload a PR on it :)
we will try to push it immediately

**Comment by idanl21** [comment]
PR - https://github.com/Opster/opensearch-k8s-operator/pull/460

**Comment by idanl21** [comment]
PR waiting for review and merge, closing issue
