### ISSUE TITLE
Disabling security audit logs

### ISSUE THREAD

**Issue by balpert89** [Opster/opensearch-k8s-operator#454]
Hi,

I did not find any means to disable the audit logs on opensearch with the operator. What is the recommended way to put in the required configuration `opensearch.security.audit.enabled: false` into the configmap item `opensearch-config/opensarch.yml`?

For a bit of context, we see around 30-40Gi daily growth on the audit index and it does not give us any advantage for now.

**Comment by balpert89** [comment]
Another approach is to have the operator remove the line `plugins.security.audit.type: "internal_opensearch"` which is added as a default here https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/reconcilers/configuration.go#L69

Please add (maybe on the CRD) a switch to enable or disable audit logs.

**Comment by idanl21** [comment]
Hey :)
you can always add additional configuration to `Opensearch.yaml` file. it should help you.
take a look at our guide :
https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#configuring-opensearchyml:~:text=in%20later%20sections.-,Configuring%20opensearch.yml,-The%20Operator%20automatically

closing the issue for now, let me know if you need anything  :)

**Comment by hsiam261** [comment]
Setting `opensearch.security.audit.enabled` to false doesn't even disable audit logs. So additional Config will not work. We still need a flag to enable or disable audit logs.
