### ISSUE TITLE
Allow setting securityContext for operator deployment/pod

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#457]
Currently there is not way to set the security context for the operator pod itself. #373 is open to allow for security context for cluster pods but I think we should be able to set these for the operator pod too. 

I think this can be easily added through the helm itself.

**Comment by idanl21** [comment]
added PR for it - https://github.com/Opster/opensearch-k8s-operator/pull/461

**Comment by ajaykumarmandapati** [comment]
Any blockers to get this moving? would be great to have this implemented directly in the chart
