### ISSUE TITLE
securityadmin interaction with Terraform managed ACLs

### ISSUE THREAD

**Issue by angeloxx** [Opster/opensearch-k8s-operator#462]
In a Opster-based cluster we manage basic configuration of local users and local permission via CRD and additional configuration (Indexs, LDAP-related roles) via Terraform without the operator. Due this approach, securityadmin.sh managed by Opster Operator erase all security-related configuration when it run as explained in https://opensearch.org/docs/latest/security/configuration/security-admin#a-word-of-caution. 

Viable options are:

- apply only files mounted/specified by the user (currently the opensearch-securityconfig-update container applies config.yml, internal_users.yml, roles.yml and roles_mapping.yml)
- disable opensearch-securityconfig-update after the cluster init or a flag to disable or force it

**Comment by swoehrl-mw** [comment]
Hi @angeloxx. There is already discussion about securityadmin and CRDs conflicting in #254. So unless you think your situation is different I'm gonna close this issue as a duplicate.

**Comment by angeloxx** [comment]
I agree with you. We managed the need changing the opensearch-securityconfig-update procedure. At the moment:
* we download via securiyadmin the current configuration
* use https://github.com/OndraZizka/yaml-merge and merge new yaml configuration with downloaded one
* apply obtained configuration via securityadmin

We can close this issue as duplicated, but we solved the issue in this way.
