### ISSUE TITLE
Provide a Helm chart to install OpenSearch cluster

### ISSUE THREAD

**Issue by IshaGirdhar** [Opster/opensearch-k8s-operator#463]
**Problem Statement:**
Currently, we do not have the option to install opensearch cluster using Helm the way we provide it for the operator. Users are required to use kubectl to install the cluster using OpenSearchCluster custom resource (CR). Therefore, providing an option to install an OpenSearch cluster using Helm will simplify the installation process and make it easier for users to set up their entire environment.

**Solution**
1. Create a Helm chart for the opensearch-cluster installation that includes all necessary components(Create a Helm template for the OpenSearchCluster custom resource (CR) that allows users to specify their desired configuration for the OpenSearch-cluster installation.)
2. Add the Helm chart to the charts directory and make it available for users to download and use.
3. Test the Helm chart and template to ensure that the installation process is smooth and error-free.
4. Update the Opster documentation to include instructions for using the Helm chart to install OpenSearch-cluster.
5. Release the updated Opster version with the new feature to the users.

**Comment by idanl21** [comment]
Hey @IshaGirdhar 
Thanks for the suggestion, it is a simple and useful tool. right now we dont have the time for it cause we focusing about improving the project functionalities, but i do hope that we will get to it soon, you are always welcome to join us and create a PR about it :)

**Comment by IshaGirdhar** [comment]
Thanks @idanl21 for the response. Yes I will be happy to contribute, have started working on it already. Will create a PR soon.

**Comment by IshaGirdhar** [comment]
> @IshaGirdhar Good to know! it is a blessed action, please let me know if you need any thing. also, you can share with me your Email address so i will join you to our maintainers slack channel .
Sure,  ishagirdhar@oracle.com is my email id.

**Comment by swoehrl-mw** [comment]
Implemented with #478. Closing issue as completed.
