### ISSUE TITLE
SecurityConfig update job overrides OpenSearchRole and OpenSearchUserRoleBinding

### ISSUE THREAD

**Issue by ekarlso** [Opster/opensearch-k8s-operator#467]
Should it be overriding the roles and bindings you provide via CRDs ?

**Comment by dbason** [comment]
I don't think it should, but there may be some weird behaviour from built in users and roles, or if the same users are specified in the security config files.  Are you able to provide us an example of how to reproduce this?

**Comment by christiancarle-bakery** [comment]
Hi @ekarlso and @dbason, we have also seen this issue.
We have created a role through manifest. When we rerun the security-config job the role created through manifest is wiped from the opensearch console. It is still visible in the k8s cluster, ```kubectl get opensearchroles.opensearch.opster.io -A```. When I delete the role manifest from the k8s cluster our gitops tool will recreate it and it will come back to the opensearch cluster.

**Comment by KannappanSomu** [comment]
@dbason @swoehrl-mw 

+1 

We have below [defaults files from opensearch security repo](https://github.com/opensearch-project/security/tree/main/config) defined as security config secret , cluster is created properly with all required roles and tenants.
then we create some end user role,  mappings & tenants with API calls. 

After this , when the security config job is restarted or deleted, job runs and  it deletes all tenants / role mapping that was created previously using API calls . 
How can we persist both , the tenants created via API and security config , if the security config  job is restated or deleted ? 

![image](https://user-images.githubusercontent.com/55806176/229608846-310bbd41-d2e9-47b6-ba19-07525823a72c.png)

**Comment by swoehrl-mw** [comment]
@KannappanSomu There is some discussion about the problem of CRDs and securityconfig interfering with each other in #254 .

Sadly at the moment it is not possible to use the securityconfig-update job and the CRDs at the same time.

**Comment by saketmht** [comment]
@swoehrl-mw While the ideal scenario would be the securityconfig not interfering with the user/roles created by the CRD, in this case shouldn't the operator reconcile the user/roles/rolesbinding as long the CRD for it exists? i.e. if it was deleted shouldn't it recreate it?

**Comment by swoehrl-mw** [comment]
@saketmht 

>  [...] in this case shouldn't the operator reconcile the user/roles/rolesbinding as long the CRD for it exists?

The default logic of user-related reconcilers is that they only run if the CRD is changed. So they do not continously compare CRD and opensearch api.

**Comment by saketmht** [comment]
@swoehrl-mw 

> The default logic of user-related reconcilers is that they only run if the CRD is changed. So they do not continously compare CRD and opensearch api.

Do you think this behavior is correct? IMO the reconciler should check if the created user still exists or not and recreate it. The user should only be deleted once the crd is deleted.
