### ISSUE TITLE
unknown field "initHelper" in io.opster.opensearch.v1.OpenSearchCluster.spec

### ISSUE THREAD

**Issue by vsankarapu** [Opster/opensearch-k8s-operator#471]
working in an offline environment and the cluster cannot access the registry , so need to change the init images 
however when I tried to use the initHelper getting the error 

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(OpenSearchCluster.spec): unknown field "initHelper" in io.opster.opensearch.v1.OpenSearchCluster.spec
helm.go:84: [debug] error validating "": error validating data: ValidationError(OpenSearchCluster.spec): unknown field "initHelper" in io.opster.opensearch.v1.OpenSearchCluster.spec

client version is Major:"1", Minor:"21", GitVersion:"v1.21.12"
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12"

apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: sma
spec:
  initHelper:
   image: "mycustomrepo.cr/mycustombusybox:myversion"
   imagePullPolicy: IfNotPresent
  general:
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    version: {{ .Values.image.tag | quote }}
    httpPort: 9200
    vendor: opensearch
    serviceName: {{ .Values.clusterName }}
    setVMMaxMapCount: true

**Comment by idanl21** [comment]
Hey @vsankarapu 
can I ask in which version of the Operator are you using ?

**Comment by vsankarapu** [comment]
@idanl21  public.ecr.aws/opsterio/opensearch-operator:v2.0 is the image we are using or operator

**Comment by idanl21** [comment]
Thats strage cause the InitHelper should be inside of the CRD from version v2.0.
can you please run `kubecl describe crd opensearchclusters.opensearch.opster.io` and send us here the results?

**Comment by idanl21** [comment]
Closing that issue, if you face it again, please reopen
