### ISSUE TITLE
securityContext for the securityconfig-update job

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#472]
In my last PR #456 , I added support to specify securityContext for the cluster and the dashboards pods but I missed the securityconfig-update pod. I can raise a PR for this but wanted to clarify whether to:

- Use the same values provided for cluster pods 
- Allow specifying separate values for the securityconfig-update job

IMO, it makes sense to just use the same values as the cluster pods for the update job as well since they both use the same image.

**Comment by idanl21** [comment]
Sounds good @saketmht 
Waiting for PR :)

**Comment by Raniz85** [comment]
Is there any upcoming release that will include this? I'm kinda blocked :)

**Comment by Raniz85** [comment]
@idanl21 Any chance of a release soon?

**Comment by swoehrl-mw** [comment]
Hi @Raniz85. We don't have concrete plans for a new release yet, but my guess is within the next few weeks.
