### ISSUE TITLE
ServiceMonitor Feature Thoughts

### ISSUE THREAD

**Issue by rhysxevans** [Opster/opensearch-k8s-operator#487]
Hi

I am having trouble migrating from my own servicemonitor setup (manual `kubectl apply -f servicemonitor.yaml` type thing ) to the crd based one. The following is what I am seeing, and I may be wrong and apologies if I am

1) When moving the monitoring plugin from `spec.general.pluginsList` to `spec.general.monitoring.pluginUrl` , I am not seeing the plugin being installed. I am also not seeing where the `spec.general.monitoring.pluginUrl` is being added to the plugin list [here](https://github.com/rhysxevans/opensearch-k8s-operator/blob/326ac1d796d288b9785760a5fbc04792e73d5b99/opensearch-operator/pkg/builders/cluster.go#L236-L237)  or anywhere else
2) Would [this](https://github.com/rhysxevans/opensearch-k8s-operator/blob/326ac1d796d288b9785760a5fbc04792e73d5b99/opensearch-operator/pkg/builders/cluster.go#L1123-L1124) just not be easier to set to `http` as there is already a service (service/clustername) setup that "points" `http` to `9200` ?

```
kubectl -n cluster1 describe service/cluster1

Name:              cluster1
Namespace:         cluster1
Labels:            opster.io/opensearch-cluster=cluster1
Annotations:       banzaicloud.com/last-applied:
                  UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWyUks2O2zAMhN+FZ3nrrGO362O39wRN0UuRAy3TjRBFEig6PQR690JO4Py0QLA3ezTzYUjwBBjMT+JovIMWjgtQsD...
Selector:          opster.io/opensearch-cluster=cluster1
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                192.168.5.15
IPs:               192.168.5.15
Port:              http  9200/TCP
TargetPort:        9200/TCP
Endpoints:         100.64.139.12:9200,100.64.141.115:9200,100.64.141.199:9200
Port:              transport  9300/TCP
# Please edit the object below. Lines beginning with a '#' will be ignored,
TargetPort:        9300/TCP
Endpoints:         100.64.139.12:9300,100.64.141.115:9300,100.64.141.199:9300
Port:              metrics  9600/TCP
TargetPort:        9600/TCP
Endpoints:         100.64.139.12:9600,100.64.141.115:9600,100.64.141.199:9600
Port:              rca  9650/TCP
TargetPort:        9650/TCP
Endpoints:         100.64.139.12:9650,100.64.141.115:9650,100.64.141.199:9650
Session Affinity:  None
Events:            <none>
```

3) When viewing the crd based servicemonitor I see this weird "clock" in the port, any ideas? I don't see this on my manually created servicemonitor

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWycUttuEzEU/Jd59jYJSQP4DcFjRCWKeIkidNZ70ph4bcs+2wpF/gZ+hW/iS5CzJb2IIto3e45nPGc0B/Qs1JEQ9AGOWna5nkLMwunMhkmI7DNTMrvGuKGi0NjalOV0Lwqeen6MN33wVkLCOM6RTH1zT/ChjEK48Zw+8ZYTe8MZen0ARfuFU7bBP+Ce3Tm8nkGhdcHsLyr/AzuW43NJAyuY4CUF56rxEdlb30HjIrK/PIq9Pzn42x5QGGwltMv5lMxi2sxebd82i+XrrnkzJ2qW8/Nt2y2mM27PUTZFIUc2NUb2XQzWy7hKS9mad4Ps6ihSzjchdfW85+/Qd8gTcd4L7jZZ669q+EPmNDL+SJ2Q50kVBeuF0zU5aMynGQqRql9MvsYUepYdD3nSsyRrjtOQBBq/fvxE2Sh8C+2qduh/qnDJjk3F9AE9idl9rBPo9dMNqdHG0H2mdMWyui3r+t9l3Sjkxz+tXtjzoiDP+ruU3wEAAP//UEsHCMePMOh1AQAAYQMAAFBLAQIUABQACAAIAAAAAADHjzDodQEAAGEDAAAIAAAAAAAAAAAAAAAAAAAAAABvcmlnaW5hbFBLBQYAAAAAAQABADYAAACrAQAAAAA=
  creationTimestamp: "2023-04-14T15:40:40Z"
  generation: 3
  labels:
    opster.io/opensearch-cluster: cluster1
  name: cluster1-monitor
  namespace: opensearch-cluster1
  ownerReferences:
  - apiVersion: opensearch.opster.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: OpenSearchCluster
    name: cluster1
    uid: b630ac40-12f9-467d-83aa-635fbd401eb5
  resourceVersion: "6792461"
  uid: 74ae8033-4fd6-4438-92d1-8fdc0af84e2b
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: cluster1-opensearch-monitoring
      username:
        key: username
        name: cluster1-opensearch-monitoring
    bearerTokenSecret:
      key: ""
    interval: 30s
    path: /_prometheus/metrics
    port: ⏰
  jobLabel: cluster1-monitor
  namespaceSelector:
    matchNames:
    - opensearch-cluster1
  podTargetLabels:
# Please edit the object below. Lines beginning with a '#' will be ignored,
  - opster.io/opensearch-cluster
# Please edit the object below. Lines beginning with a '#' will be ignored,
  selector:
    matchLabels:
      opster.io/opensearch-cluster: cluster1
  targetLabels:
  - opster.io/opensearch-cluster
```

4)  Can we add support for the `scheme` ? In particular I need to set it to `https`
5) Can we add support for the `TLSConfig` ? In particular I need to set `insecureSkipVerify = True` at this point

Any help/advice is appreciated

Thanks

**Comment by swoehrl-mw** [comment]
Hi @rhysxevans 
> 1. When moving the monitoring plugin from spec.general.pluginsList to spec.general.monitoring.pluginUrl , I am not seeing the plugin being installed. I am also not seeing where the spec.general.monitoring.pluginUrl is being added to the plugin list [here](https://github.com/rhysxevans/opensearch-k8s-operator/blob/326ac1d796d288b9785760a5fbc04792e73d5b99/opensearch-operator/pkg/builders/cluster.go#L236-L237) or anywhere else

Good catch, looks like this was somehow missed during implementation of the feature.

> 2. Would [this](https://github.com/rhysxevans/opensearch-k8s-operator/blob/326ac1d796d288b9785760a5fbc04792e73d5b99/opensearch-operator/pkg/builders/cluster.go#L1123-L1124) just not be easier to set to http as there is already a service (service/clustername) setup that "points" http to 9200 ?

It would at least be more consistent.

> 3. When viewing the crd based servicemonitor I see this weird "clock" in the port, any ideas? I don't see this on my manually created servicemonitor

Haven't investigated, but my guess is that somewhere the port integer is converted to a string and wrongly treated as the bytes of a unicode character.

> 4. Can we add support for the scheme ? In particular I need to set it to https
> 5. Can we add support for the TLSConfig ? In particular I need to set insecureSkipVerify = True at this point

Fine with me.
