### ISSUE TITLE
Move CRDs from Helm templates to the crds folder

### ISSUE THREAD

**Issue by AndersBennedsgaard** [Opster/opensearch-k8s-operator#499]
When installing CRDs with Helm, you should use the `crds/` folder instead of placing them in `templates/`.
This makes it possible to skip CRD installation with Helm, using the `--skip-crds` flag (which I want to use, since Helm doesn't really support working with CRDs)

**Comment by swoehrl-mw** [comment]
Unfortunately just moving the CRDs to the `crds/` folder creates other problems (for example CRDs do not get updated). So even if we wanted to use that route it would need flanking changes to the documentation and information for users how to handle upgrades.
There is an open discussion in #180 about how to handle CRDs.

Until that is properly discussed and we are clear which way to go and how to handle upgrades, I feel I have to rollback the PR for this issue as I believe leaving it in would create more problems now than it solves.

What we can do as a short-term workaround is updating the helm chart and wrapping the CRD definitions with an if so installation of them can be skipped by providing a parameter (something like `skipInstallCRDs`, a bit like [cert-manager does it](https://cert-manager.io/docs/installation/helm/#option-2-install-crds-as-part-of-the-helm-release) ). 

cc @idanl21

**Comment by AndersBennedsgaard** [comment]
@swoehrl-mw sorry, I didn't notice #180. :confused:
