### ISSUE TITLE
Searchable snapshots are GA

### ISSUE THREAD

**Issue by rhysxevans** [Opster/opensearch-k8s-operator#503]
Searchable Snapshots have reach GA in 2.7 

https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.7.0.md
https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot/

We will need to update the code to not apply the experimental flag if cluster version is 2.7 or above

Ref: https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/builders/cluster.go#L180

**Comment by rhysxevans** [comment]
PR Raised https://github.com/Opster/opensearch-k8s-operator/pull/504

**Comment by swoehrl-mw** [comment]
Closing this issue as it was implemented with PR #504.
