### ISSUE TITLE
Opensearch 2.7 Searchable Snapshots support issue

### ISSUE THREAD

**Issue by rhysxevans** [Opster/opensearch-k8s-operator#513]
Hi

Please note that with the support of opensearch 2.7 mentioned [here](https://github.com/Opster/opensearch-k8s-operator/commit/bc594c356ed7872c88d66fdd9bc35943a714d0d7). The operator will still continue to deploy the experimental flag `-Dopensearch.experimental.feature.searchable_snapshot.enabled=true` if the `search` role is added to the nodes.

The fix was merged here https://github.com/Opster/opensearch-k8s-operator/pull/504, and until a new release is cut people may see issues.

Thanks

**Comment by idanl21** [comment]
merged the FIX
https://github.com/Opster/opensearch-k8s-operator/pull/504
closing
