### ISSUE TITLE
Make operator logging level configurable and change default level to info instead of debug

### ISSUE THREAD

**Issue by sergeiwaigant** [Opster/opensearch-k8s-operator#520]
Hi guys.

I am looking for a way to configure the log level for the Operator Controller Manager which is logging on "debug" level by default.
I guess its via the extraEnvs in the Helmchart - can anyone advice how to do that or find the documentation?

Regards
Sergei

**Comment by swoehrl-mw** [comment]
Hi @sergeiwaigant. Unfortunately AFAIK the loging library we use does not have integrated support to change the log level via environment variables. We would need to implement this ourselves in the operator init code. 
I'll mark this isse as a feature request, as this is a good feature to have.

**Comment by swoehrl-mw** [comment]
From the code it looks to be hardcoded (https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/main.go#L69), so I don't think there is currently a way to change the level without modifying the code.

**Comment by aschi1** [comment]
This would be a very welcome change, currently the `debug` logs produce quite a lot of records

**Comment by aschi1** [comment]
Hi @swoehrl-mw when can we expect this to release? As of now its still not included in the latest release `v2.3.2`. Thanks for the info

**Comment by swoehrl-mw** [comment]
Hi @aschi1. It will be included in the next feature release (2.4.0), as it's not a bugfix it was not included in the patch releases (2.3.1 or 2.3.2). When the next release will be I cannot tell. I'd say soon-ish, but no concrete timeframe.
