### ISSUE TITLE
Security config update job doesn't use service account

### ISSUE THREAD

**Issue by Raniz85** [Opster/opensearch-k8s-operator#533]
In OpenShift or OKD, the service account is used to grant pod a different SecurityContextConstraint.

However, since the security config update job doesn't use the service account defined in spec.general.serviceAccount it won't use custom SCCs.

**Comment by swoehrl-mw** [comment]
Hi @Raniz85. Thanks for reporting this, sounds like an easy change.

**Comment by swoehrl-mw** [comment]
Just saw there is already an existing issue for this (#392), closing this one as a duplicate.

**Comment by Raniz85** [comment]
Oups, my bad, sorry for the spam
