### ISSUE TITLE
Add additionalPrinterColumns to CRD to get more details about clusters 

### ISSUE THREAD

**Issue by prabhakartalari** [Opster/opensearch-k8s-operator#539]
Hi Team,

Currently when we do "kubectl get os" the output is as per below, which is not having much information about the clusters like health, number of nodes, phase etc..

NAME                    AGE
my-first-cluster    28d

Expected output is as per below with the latest CRD changes

NAME               HEALTH   NODES   VERSION   PHASE     AGE
my-first-cluster  GREEN      6            2.7.0     RUNNING   28d

Please find the attachment's for the current CRD and Updated CRD.

[opensearch-crd.log](https://github.com/Opster/opensearch-k8s-operator/files/11818849/opensearch-crd.log)
[opensearch-crd-new.log](https://github.com/Opster/opensearch-k8s-operator/files/11818850/opensearch-crd-new.log)

I hope this will help when we want to list out the clusters with the basic information.

Thanks,

**Comment by swoehrl-mw** [comment]
Hi @prabhakartalari Thanks for suggesting this. Would you be willing to create a PR for this change?
