### ISSUE TITLE
Support annotations on StatefulSet

### ISSUE THREAD

**Issue by Raniz85** [Opster/opensearch-k8s-operator#544]
Currently, it is only possible to set annotations on the pods but we need to set annotations on the StatefulSet itself.

This would enable use of (for example) [Reloader](https://github.com/stakater/Reloader) to automatically restart pods when referenced secrets has changed.

**Comment by swoehrl-mw** [comment]
Hi @Raniz85. this sounds like a rather simple change.
Just to clarify, would it be enough to add the same annotations to the sts as for the pods (as is done with the labels already) or would you need to set them independently?

**Comment by Raniz85** [comment]
For our usecase that would be enough.

I've also seen the annotations from the CR be added to the STS (MinIO Operator does it this way).

Either of those ways would work for us.
