### ISSUE TITLE
Make the "seconds" field for Toleration optional.

### ISSUE THREAD

**Issue by yolkov** [Opster/opensearch-k8s-operator#546]
omc 1.9.7

<img width="267" alt="image" src="https://github.com/Opster/opensearch-k8s-operator/assets/1337317/88a5c87e-220b-4437-a1dd-46cd6055e958">

<img width="740" alt="image" src="https://github.com/Opster/opensearch-k8s-operator/assets/1337317/27b842e4-09d5-4d19-8399-99e5f9fe044d">

If I specify seconds, we get the following error
`create Pod test-master-0 in StatefulSet test-master failed error: Pod "test-master-0" is invalid: spec.tolerations[0].effect: Invalid value: "NoSchedule": effect must be 'NoExecute' when tolerationSeconds is set
`

**Comment by idanl21** [comment]
Hey @yolkov 
Thanks for the issue, it is a bug
we are working on new version that solved that one, will update you here when it will be released

**Comment by swoehrl-mw** [comment]
Closing as issue is not relevant for the operator itself.
