### ISSUE TITLE
CRD's not in the helm package.

### ISSUE THREAD

**Issue by surikbs** [Opster/opensearch-k8s-operator#574]
Hi Team, While we run helm dependency update before installing the operator. We could see two of the crd's no included in the helm package. The crds are for the opensearch tenant and action groups. Request you to include them in the helm package. It would be really helpful to include them in the package.

The screenshot: 
![image](https://github.com/Opster/opensearch-k8s-operator/assets/19169786/57131da9-9f72-464a-8f6a-e9c474eac3c7)

**Comment by swoehrl-mw** [comment]
Hi @surikbs. These two CRDs are part of features that are not yet part of a release. As such it is expected that they are not included in the helm package for 2.3.1. Expect them to be part of the next release 2.4.0, we don't have a timeframe yet but hopefully in a few weeks.
