### ISSUE TITLE
So, if I absolutely have to use HTTP and not HTTPS I cannot use the operator?

### ISSUE THREAD

**Issue by NeckBeardPrince** [Opster/opensearch-k8s-operator#579]
I'm attempting to use Opensearch with our self-hosted Gitlab and the Advanced Search feature. However, Gitlab requires either HTTP or a valid, non-self-signed cert if connecting via HTTPS. So, configuring Gitlab to connect to the in-cluster https://opensearch-cluster.opensearch.svc.cluster.local:9200 is going to cause Opensearch to throw the following error.

```
Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
```

Can I use HTTP if I use the helm [chart](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml)?

**Comment by swoehrl-mw** [comment]
Hi @NeckBeardPrince. You are correct that the operator does currently not support disabling HTTPS. 
Gitlab should have an option to provide it a custom CA certificate (I think you need to add it to the CA bundle, but no idea about the details as I've never worked with that feature in Gitlab). Then you can extract the CA cert from the secret `<clustername>-ca` and provide it to gitlab. Another option would be to route the requests through an ingress controller or proxy that provides a properly signed certificate (e.g. with LetsEncrypt).

If you really need HTTP, then yes, the helm chart should allow you to configure this.
