### ISSUE TITLE
[Question] Openshift support

### ISSUE THREAD

**Issue by indiealexh** [Opster/opensearch-k8s-operator#589]
I saw in this post: https://opster.com/guides/opensearch/opensearch-basics/set-up-run-opensearch-kubernetes-with-operator/

That openshift support was coming soon, but did not see it on the roadmap.

When is this expected to become a priority? I have opensearch running in my openshift cluster at the moment, but would love to see it in my operators list and have it work out of the box than need custom changes made to permissions, routes etc.

**Comment by swoehrl-mw** [comment]
Hi @indiealexh. The roadmap was just updated to include OpenShift.

Please note that OpenShift support is not a priority for any of the maintainers and we are looking for community contributions on that topic. As such there is no timeline or expectation.
