### ISSUE TITLE
Seeing a memory leak causing the operator to get oomkilled with 2.4.0

### ISSUE THREAD

**Issue by RandellP** [Opster/opensearch-k8s-operator#612]
Recently updated our operator to 2.4.0.  Turned on monitoring as well.
It takes about 10hours of a steady memory usage climb before it gets oomkilled.  So it is a slow but steady grow.

I looked at the operators logs and it is just the same messages cycling over and over with nothing special in them.
```
{"level":"info","ts":"2023-09-18T23:49:27.312Z","msg":"The existing disk size 500Gi is same as passed in disk size 500Gi","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"my-infra","namespace":"monitor"},"namespace":"monitor","name":"my-infra","reconcileID":"c3bd8736-f8aa-4991-8b90-2472faf42eb7"}
{"level":"info","ts":"2023-09-18T23:49:37.440Z","msg":"Reconciling OpenSearchCluster","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"my-infra","namespace":"monitor"},"namespace":"monitor","name":"my-infra","reconcileID":"6e398e47-461b-410d-bc9e-548592eccaa8","cluster":{"name":"my-infra","namespace":"monitor"}}
{"level":"info","ts":"2023-09-18T23:49:37.452Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"my-infra","namespace":"monitor"},"namespace":"monitor","name":"my-infra","reconcileID":"6e398e47-461b-410d-bc9e-548592eccaa8","interface":"transport"}
{"level":"info","ts":"2023-09-18T23:49:37.457Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"my-infra","namespace":"monitor"},"namespace":"monitor","name":"my-infra","reconcileID":"6e398e47-461b-410d-bc9e-548592eccaa8","interface":"http"}
0 https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.5.0.0/prometheus-exporter-2.5.0.0.zip
```

This is not happening in all of our clusters.  Only in 1 of our 2 production clusters which should be pretty much identical, just in a different region.  

I tried deleting the pod, the new one did the same thing.

Our code to setup the operator is super simple.

```
resource "helm_release" "opensearch_operator" {
  name       = "opensearch-operator"
  chart      = "opensearch-operator"
  repository = "https://opster.github.io/opensearch-k8s-operator"
  version    = var.versions.opensearch_operator

  namespace        = kubernetes_namespace.opensearch_operator.metadata.0.name
  create_namespace = false

  timeout = 600
}
```

So we didn't modify any memory settings for the operator pod or anything.
```
Limits:
      cpu:     50m
      memory:  50Mi
    Requests:
      cpu:        25m
      memory:     25Mi
```
And of course the other clusters have the same and stay steady and well below the request line.

Any ideas on what I can look at for what might be causing the leak?

**Comment by RandellP** [comment]
Yeah I saw that one.  But since it was a prod cluster I couldn't uninstall everything like they did.  That similarly would block me from using a custom build.

But... it seems to have fixed itself.  But I don't know how.

I checked the crds, deployment, secrets... none changed at the at the time the pod stopped getting OOMKilled.  The pod has a few days on it now with no kill, and the mem usage looks stable and low.  

Someone must have deployed something that triggered something to update, but I am not sure what.

If you have any other k8s resources you want me to check if they got updated around the time the problem got fixed, let me know.  Otherwise we can close this issue.

**Comment by swoehrl-mw** [comment]
Very mysterious. I can't think of any other k8s resources that could be in play here, so I'll close the issue.

I've opened a feature request to add pprof capabilities to the operator so in the future it can be easier to get memory dumps.

**Comment by albgus** [comment]
I'm also seeing this issue so I don't think it's an isolated instance. The memory usage is increasing very steadily until it crashes once every few days.

![image](https://github.com/Opster/opensearch-k8s-operator/assets/4476818/4b3b19a2-0514-45eb-92e4-5a70b3c0977a)

**Comment by RandellP** [comment]
So minor update.  The issue is back.  And only in the same clusters.  That implies it has something to do with the cluster.  My guess is some kind of event gets some bad data into the operator, and somehow that data expires (since the issue went away magically).  We are keeping an eye on it.  When it fixes itself again, I will get the time it took to fix, and maybe that will give us an idea what kind of data it might have been.   
Also....  this could be coincidence, but we saw a significant increase in metrics coming from opensearch on the clusters that have this issue, and the timing seems to align.  Still looking into that.

**Comment by ThomasRasmussen** [comment]
@RandellP  did you find any cause to this? We are seeing the same issue on multiple clusters after upgrading to operator 2.4.0 (running 2.3.2 before).
