### ISSUE TITLE
Remove `fmt.Println` on plugins

### ISSUE THREAD

**Issue by AndersBennedsgaard** [Opster/opensearch-k8s-operator#615]
https://github.com/Opster/opensearch-k8s-operator/blob/7bdbfc08fe92193ad792508f27ea5eff1eefdfc4/opensearch-operator/pkg/helpers/reconcile-helpers.go#L134 results in weird log lines in the operator coming from `spec.general.pluginsList` in the OpenSearchCluster resource, such as

```log
0 repository-s3
1 https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.6.0.0/prometheus-exporter-2.6.0.0.zip
```

Could this be removed or made into a regular log line instead?

**Comment by swoehrl-mw** [comment]
Hi @AndersBennedsgaard. From my perspective this looks like a debug println during development that was accidentally left in the code and should just be removed.

**Comment by geoffrey1330** [comment]
Hi @swoehrl-mw could you please assign this issue to me so i can work on it?

**Comment by prudhvigodithi** [comment]
Thanks @geoffrey1330 I have assigned this issue to you.

**Comment by geoffrey1330** [comment]
Thanks

**Comment by geoffrey1330** [comment]
> Thanks @geoffrey1330 I have assigned this issue to you.

Thanks @prudhvigodithi
