### ISSUE TITLE
Repo is not accessible 

### ISSUE THREAD

**Issue by exela-dlambert** [Opster/opensearch-k8s-operator#668]
public.ecr.aws/opsterio/opensearch-operator

The helm chart attempts to pull from the above. There are no blocks in place. Is this no longer publically accessible?

**Comment by swoehrl-mw** [comment]
Hi @exela-dlambert 

The repo is still public and can be normally pulled:
```bash
$ docker pull public.ecr.aws/opsterio/opensearch-operator:2.4.0
2.4.0: Pulling from opsterio/opensearch-operator
Digest: sha256:f5ecdee1eec78c1ab9b5a06d0d590b2399a27402e93ffe5cc2585c5f139f1752
Status: Downloaded newer image for public.ecr.aws/opsterio/opensearch-operator:2.4.0
public.ecr.aws/opsterio/opensearch-operator:2.4.0
```

You can also see the image via the gallery: https://gallery.ecr.aws/opsterio/opensearch-operator

**Comment by exela-dlambert** [comment]
Appreciate the quick reply. I ended up finding the issue just after opened this issue request.
