### ISSUE TITLE
Operator DiskSize: to modify with String input

### ISSUE THREAD

**Issue by prudhvigodithi** [Opster/opensearch-k8s-operator#88]
Ability to add DiskSize as string rather an a fixed int value, which currently parses backend to 'Gi', user should be flexible to pass 'G' or 'Gi' and soo on.

**Background:** from doc
Limits and requests for memory are measured in bytes. We can express memory as a plain integer or as a fixed-point integer using one of these suffixes: E, P, T, G, M, K. We can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki. 

The kibibyte was designed to replace the kilobyte in those computer science contexts in which the term kilobyte is used to mean 1024 bytes. The interpretation of kilobyte to denote 1024 bytes, conflicting with the SI definition of the prefix kilo (1000), used to be common.

So, as we can see, 5G means 5 Gigabytes while 5Gi means 5 Gibibytes. They amount to:

5 G = 5000000 KB / 5000 MB
5 Gi = 5368709.12 KB / 5368.70 MB
Therefore, in terms of size, they are not the same.

**Comment by idanl21** [comment]
Can I close that issue ? @prudhvigodithi

**Comment by prudhvigodithi** [comment]
yes @idanl21 this has been fixed in this PR: https://github.com/Opster/opensearch-k8s-operator/pull/90, closing this issue.
Thank you
